"""296 reference used only by the controlled 512 resolution probe."""

from configs.dinov1_s8 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_gbsp_resolution_296_reference"
GBSP_RESOLUTION_VERSION = "gbsp_resolution_native_v1"
GBSP_RESOLUTION_VARIANT = "296-baseline"
FEATURE_CACHE_KEY = "dinov1-s8-296-reference"
DINO = dict(DINO)
DINO["feature_input_size"] = 296

FEATURE_INPUT_SIZE = 296
GRID_SIZE = 37
SUPERVISION_GRID = 68
LOSS_SIZE = 68
USE_LEGACY_68_INTERPOLATION = True

DABE_GRID = 37
DABE_LOSS_SIZE = 68
DABE_SIGMA_F = 0.10
DABE_SIGMA_C = 0.05
DABE_SIGMA_E = 0.30
DABE_BORDER_WIDTH = 2
DABE_TAU_BC = 0.30
DABE_BG_ANCHOR_TOP_PERCENT = 30.0
DABE_BG_ANCHOR_MIN_RATIO = 0.05
DABE_BG_ANCHOR_FALLBACK_TOP_PERCENT = 40.0

GBSP_BG_RATIO = 0.30
GBSP_BORDER_WIDTH = 2
GBSP_PCA_ENERGY = 0.90
GBSP_PCA_MAX_RANK = 8
GBSP_PCA_MIN_RANK = 1
GBSP_THRESHOLD = 0.58
GBSP_THRESHOLD_SELECTION = "frozen_296_baseline_threshold"
GBSP_NATIVE_TARGET_SIZE = 68
GBSP_GT_USED_FOR_GENERATION = False

