from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_relaxamb_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_lrfloor_2e5"

USE_RAST = True
RAST_VERSION = "v1.2_esa_asym"

RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21

RAST_CONFLICT_TEACHER_MULT = 0.20
RAST_EXTENT_TEACHER_MULT = 1.00
RAST_UNKNOWN_TEACHER_MULT = 0.50
RAST_OTHER_TEACHER_MULT = 1.00

RAST_POST_RESET_ENABLE = False
RAST_POST_RESET_SCALE = 0.00
RAST_POST_RESET_CONFLICT_ONLY = False
RAST_POST_RESET_USE_STATIC_LOSS = False

RAST_APPLY_TO_FINAL = True
RAST_APPLY_TO_COARSE_AUX = True
RAST_APPLY_TO_BASE_AUX = True
RAST_WEIGHTED_LOSS_NORMALIZE = True

USE_HBNS_LITE = False
HBNS_LAMBDA_MAX = 0.0

USE_EPR_POS = False
EPR_LAMBDA_MAX = 0.0

USE_ESA_ASYM = True
ESA_ASYM_VERSION = "extent_teacher_bg_routing_v1"

ESA_ASYM_START_EPOCH = 7
ESA_ASYM_RAMP_END_EPOCH = 15
ESA_ASYM_STOP_EPOCH = 21

ESA_EXTENT_TEACHER_FG_MULT = 1.00
ESA_EXTENT_TEACHER_BG_MULT = 0.50

ESA_USE_DINO_MARGIN = True
ESA_MARGIN_FG_LIKE = 0.05
ESA_MARGIN_BG_LIKE = -0.05

ESA_EXTENT_TEACHER_BG_FG_LIKE_MULT = 0.25
ESA_EXTENT_TEACHER_BG_AMBIG_MULT = 0.50
ESA_EXTENT_TEACHER_BG_BG_LIKE_MULT = 1.00

ESA_TOUCH_UNKNOWN = False
ESA_UNKNOWN_TEACHER_MULT = 0.50

ESA_FEATURE_SIZE = 37
ESA_DETACH_MASK = True
ESA_DETACH_PROTO = True

USE_ESA_DIAGNOSTIC = True
ESA_DIAG_LOG_INTERVAL_EPOCH = 1
