from configs.dinov1_s8_despl_only_teacher_cache import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_only_anchor_pbce"

USE_DESPL_ANCHOR_PBCE = True
ANCHOR_PBCE_SOURCE = "p_despl"
ANCHOR_PBCE_THETA_FG = 0.70
ANCHOR_PBCE_THETA_BG = 0.30
ANCHOR_PBCE_MIN_VALID_PIXELS = 16
ANCHOR_PBCE_LAMBDA_EARLY = 0.10
ANCHOR_PBCE_EARLY_END_EPOCH = 20
ANCHOR_PBCE_LAMBDA_LATE = 0.02
ANCHOR_PBCE_LATE_START_EPOCH = 21
ANCHOR_PBCE_LATE_END_EPOCH = 23

HEAD_TYPE = "simple"

USE_DESPL_PSEUDO = True
USE_DESPL_LIGHT_CACHE = True
P_INIT_MODE = "despl_only"
P_INIT_DESPL_WEIGHT = 1.0
P_INIT_FIXED_WEIGHT = 0.0

PSEUDO_USE_GCM = False
PSEUDO_USE_TEACHER = False
PSEUDO_USE_LOCAL_ATTN = False

USE_PSTA = False
USE_MNP = False
DINO_USE_LORA = False
USE_CNN_DETAIL_BRANCH = False
USE_AFF = False
USE_DUAL_FG_BG_HEAD = False
USE_BOUNDARY_HEAD = False

LAMBDA_MNP = 0.0
LAMBDA_LOCAL = 0.0
LAMBDA_PSTA = 0.0
LAMBDA_CONTRAST = 0.0
LAMBDA_BOUNDARY = 0.0
LAMBDA_ENTROPY = 0.0
LAMBDA_ANCHOR = 0.0

USE_LATE_DESPL_ANCHOR_LOSS = False
