from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v1_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_relaxamb_lrfloor_2e5"

USE_RAST = True
RAST_VERSION = "v1.2_relax_ambiguity"

RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21

RAST_CONFLICT_TEACHER_MULT = 0.20
RAST_EXTENT_TEACHER_MULT = 1.00
RAST_UNKNOWN_TEACHER_MULT = 0.50
RAST_OTHER_TEACHER_MULT = 1.00

RAST_STATIC_FG_CORE_MULT = 1.00
RAST_STATIC_BG_CORE_MULT = 1.00
RAST_STATIC_EXTENT_MULT = 1.00
RAST_STATIC_UNKNOWN_MULT = 1.00

RAST_APPLY_TO_FINAL = True
RAST_APPLY_TO_COARSE_AUX = True
RAST_APPLY_TO_BASE_AUX = True

RAST_POST_RESET_ENABLE = False
RAST_POST_RESET_SCALE = 0.00
RAST_POST_RESET_CONFLICT_ONLY = False
RAST_POST_RESET_USE_STATIC_LOSS = False

RAST_WEIGHTED_LOSS_NORMALIZE = True
