from configs.dinov1_s8_despl_teacher_cache import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dre_safe"

USE_DRE_SAFE_PRIOR = True
P_INIT_MODE = "safe_despl_residual"

P_INIT_DESPL_WEIGHT = 0.8
P_INIT_FIXED_WEIGHT = 0.2

DRE_SAFE_DESPL_FG_TH = 0.50
DRE_SAFE_DESPL_UNCERT_LOW = 0.35
DRE_SAFE_DESPL_UNCERT_HIGH = 0.65
DRE_SAFE_FIXED_FG_TH = 0.75
DRE_SAFE_DILATE_RADIUS = 2
DRE_SAFE_MAX_POS_RESIDUAL = 0.15
DRE_SAFE_RESIDUAL_GAMMA = 0.5
DRE_SAFE_AREA_GROWTH_MAX = 1.10
DRE_SAFE_AREA_SHRINK_MIN = 0.90
DRE_SAFE_CC_INCREASE_MAX = 3

USE_LATE_DESPL_ANCHOR_LOSS = False
LATE_DESPL_ANCHOR_LAMBDA = 0.02

USE_GCM = False
PSEUDO_USE_GCM = False
PSEUDO_USE_TEACHER = False
PSEUDO_USE_LOCAL_ATTN = False
DINO_USE_LORA = False
USE_CNN_DETAIL_BRANCH = False
USE_AFF = False
USE_DUAL_FG_BG_HEAD = False
USE_BOUNDARY_HEAD = False
USE_PSTA = False
USE_MNP = False

MAX_EPOCH = 25
LOSS_SIZE = 68
EMA_WEIGHT = 0.99
SAVE_INTERVAL = 5

HEAD_TYPE = "simple"
