from configs.dinov1_s8 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_ecst_dagp_uncgate_ndr_long45_lrfloor_2e5"

# DABE-PU v1.1 static supervision and full binary EMA-teacher supervision.
USE_DABE_PU = True
DABE_PU_VERSION = "pu_v11"
DABE_PU_ROOT = "../datasets/cache/dabe_pu_v11_pseudo_cache/dinov1-s8"
P_INIT_MODE = "dabe_pu_v11_desplsched"
P_INIT_DABE_WEIGHT = 1.0
P_INIT_DESPL_WEIGHT = 0.0
P_INIT_FIXED_WEIGHT = 0.0

TEACHER_FUSION_MODE = "dabe_pu_despl_sched"
USE_DABE_PU_DESPL_SCHEDULE = True
USE_DABE_PU_STATIC_LOSS = True
DABE_PU_STATIC_TARGET_MODE = "soft"
STATIC_WEIGHT_MODE = "cache"
USE_DABE_PU_HARD_STATIC_TARGET = False
USE_TEACHER_BINARY_FULL_LOSS = True
USE_TEACHER_SOFT_FULL_LOSS = False
USE_TEACHER_CONF_LOSS = False
TEACHER_TARGET_MODE = "binary"
DABE_PU_WEIGHTED_BCE_EPS = 1e-6
LAMBDA_DABE_PU_STATIC = 1.0

DABE_PU_DESPL_STAGE_START = 1
DABE_PU_DESPL_STAGE_END = 20
DABE_PU_DESPL_STATIC_START = 1.00
DABE_PU_DESPL_STATIC_END = 0.05
DABE_PU_DESPL_TEACHER_START = 0.00
DABE_PU_DESPL_TEACHER_END = 0.95
DABE_PU_DESPL_TEACHER_ONLY_START = 21

FUSION_ORIG_DECAY_EPOCHS = 20
FUSION_HOLD_FIXED_WEIGHT = 0.05
FUSION_MIN_FIXED_WEIGHT = 0.05
TEACHER_FUSION_MAX_WEIGHT = 1.0
TEACHER_FUSION_PRE_RESET_EPOCHS = 19

# ECST is the only teacher-loss pixel router in the clean path.
USE_ECST = True
ECST_VERSION = "v1_state_conditional_asymneg"
ECST_START_EPOCH = 7
ECST_RAMP_END_EPOCH = 15
ECST_STOP_EPOCH = 21

ECST_MEMORY_UPDATE_START_EPOCH = 1
ECST_MEMORY_UPDATE_END_EPOCH = 20
ECST_TEMPORAL_RHO = 0.90
ECST_MIN_HISTORY = 3
ECST_MEMORY_DTYPE = "float16"
ECST_USE_PREUPDATE_STATS = True
ECST_RESET_MEMORY_AT_FINETUNE_RESET = True

ECST_TEMPORAL_SCOPE = "extent_teacher_bg_only"
ECST_VARIANCE_TAU = 0.02
ECST_CONF_GAMMA = 1.0
ECST_INSUFFICIENT_HISTORY_MODE = "dino_only"
ECST_CORE_CONFLICT_WEIGHT = 0.20
ECST_EXTENT_FG_WEIGHT = 1.00
ECST_EXTENT_BG_WEIGHT_FLOOR = 0.25
ECST_EXTENT_DINO_LAMBDA = 1.386294
ECST_MARGIN_TAU = 0.05
ECST_UNKNOWN_WEIGHT = 0.50
ECST_WEIGHT_MIN = 0.20
ECST_WEIGHT_MAX = 1.00

ECST_FEATURE_SIZE = 37
ECST_DETACH_PROTO = True
ECST_DETACH_MASK = True
ECST_MARGIN_FG_LIKE = 0.05
ECST_MARGIN_BG_LIKE = -0.05
ECST_APPLY_TO_FINAL = True
ECST_APPLY_TO_COARSE_AUX = True
ECST_APPLY_TO_BASE_AUX = True
ECST_LOG_INTERVAL_EPOCH = 1
ECST_DEBUG_FIRST_BATCH = True

# Original DAGP-Safe coarse path.
HEAD_TYPE = "dagp_safe"
USE_DAGP_SAFE_HEAD = True
DAGP_SAFE_HIDDEN = 64
DAGP_SAFE_TOPK = 12
DAGP_SAFE_TAU = 0.07
DAGP_SAFE_ALPHA_MAX = 0.05
DAGP_SAFE_GAMMA_MAX = 0.03
DAGP_SAFE_WARMUP_EPOCH = 6
DAGP_SAFE_RAMP_START_EPOCH = 7
DAGP_SAFE_RAMP_END_EPOCH = 15
DAGP_SAFE_USE_PROB_GATE = True
DAGP_SAFE_PROB_GATE_SIGMA = 0.25
DAGP_SAFE_PROB_GATE_EPS = 1e-6
DAGP_SAFE_USE_UNCERTAINTY_OUTPUT_GATE = True
DAGP_SAFE_UNCERTAINTY_MIN = 0.0
DAGP_SAFE_UNCERTAINTY_MAX = 1.0
DAGP_SAFE_UNCERTAINTY_POWER = 1.0
DAGP_SAFE_AFFINITY_DETACH = True
DAGP_SAFE_UNCERTAINTY_DETACH = True
DAGP_SAFE_EXCLUDE_SELF = True
DAGP_SAFE_ZERO_INIT_GRAPH_PRED = True
DAGP_SAFE_ZERO_INIT_VALUE = False
DAGP_SAFE_DEBUG_FIRST_BATCH = True

USE_BASE_AUX_LOSS = True
BASE_AUX_NORMALIZE = True
LAMBDA_BASE_AUX = 0.50
LAMBDA_BASE_AUX_AFTER_RESET = 0.30

# Original NDR-v1 detail residual path.
USE_NDR_BRANCH = True
USE_NDR_COARSE_AUX = True
LAMBDA_NDR_COARSE_AUX = 0.50
NDR_IN_CHANNELS = 5
NDR_HIDDEN = 32
NDR_NUM_LAYERS = 3
NDR_GN_GROUPS = 4
NDR_ACT = "gelu"
NDR_INPUT_RGB = True
NDR_INPUT_SOBEL = True
NDR_INPUT_COARSE_PROB = True
NDR_USE_GN = True
NDR_USE_EDGE_GATE = True
NDR_USE_UNCERTAINTY_GATE = True
NDR_GATE_MODE = "uncertainty_edge_boost"
NDR_BETA_MAX = 0.10
NDR_RESIDUAL_CLIP = 2.0
NDR_ZERO_INIT_OUT = True
NDR_WARMUP_EPOCH = 6
NDR_RAMP_START_EPOCH = 7
NDR_RAMP_END_EPOCH = 15
NDR_USE_RES_REG = False
NDR_RES_REG_WEIGHT = 0.001
NDR_DEBUG_FIRST_BATCH = True

# Original optimization, reset, checkpoint, and evaluation protocol.
LR = 0.0006
LR_POLICY = "step_floor"
USE_LR_FLOOR = True
LR_FLOOR = 2e-5
LR_FLOOR_MODE = "global"
LR_LINEAR_STAGE1_EPOCHS = 19
LR_LINEAR_STAGE2_EPOCHS = 0
LR_FLOOR_APPLY_AFTER_SCHEDULER_STEP = True
LR_FLOOR_APPLY_AFTER_FINETUNE_RESET = True

FINETUNE_RESET_EPOCH = 20
FINETUNE_RESET_TIMING = "after_epoch"
FINETUNE_RESET_REBUILD_OPTIMIZER = True
FINETUNE_RESET_REBUILD_SCHEDULER = True
FINETUNE_RESET_GLOBAL_STEP = True
FINETUNE_RESET_TEACHER = True
FINETUNE_RESET_FORCE_LR_FLOOR = True
FINETUNE_RESET_LR = 2e-5

MAX_EPOCH = 45
max_epoch = 45
SAVE_EVERY_EPOCH = True
SAVE_INTERVAL = 1
