from configs.dinov1_s8_despl_dagp_uncgate_ndr_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_puconf_lrfloor_2e5"

USE_DABE_PU = True
DABE_PU_VERSION = "pu_v11"
DABE_PU_ROOT = "../datasets/cache/dabe_pu_v11_pseudo_cache/dinov1-s8"

P_INIT_MODE = "dabe_pu_v11"
P_INIT_DESPL_WEIGHT = 0.0
P_INIT_FIXED_WEIGHT = 0.0
USE_DABE_PSEUDO = False
USE_DABE_AWARE_LOSS = False
USE_DABE_TVERSKY_LOSS = False
USE_DABE_AREA_GUARD = False

# Keep DESPL light cache only for pseudo_fixed/pseudo_despl diagnostics.
USE_DESPL_PSEUDO = True
USE_DESPL_LIGHT_CACHE = True

TEACHER_FUSION_MODE = "dabe_pu_conf"
USE_DABE_PU_STATIC_LOSS = True
USE_TEACHER_CONF_LOSS = True

FINETUNE_RESET_EPOCH = -1
FINETUNE_RESET_REBUILD_OPTIMIZER = False
FINETUNE_RESET_REBUILD_SCHEDULER = False
FINETUNE_RESET_GLOBAL_STEP = False
FINETUNE_RESET_TEACHER = False

DABE_PU_STATIC_E1_E6 = 1.00
DABE_PU_TEACHER_E1_E6 = 0.00
DABE_PU_STAGE2_START = 7
DABE_PU_STAGE2_END = 20
DABE_PU_STATIC_STAGE2_START = 1.00
DABE_PU_STATIC_STAGE2_END = 0.40
DABE_PU_TEACHER_STAGE2_START = 0.00
DABE_PU_TEACHER_STAGE2_END = 0.60
DABE_PU_AFTER_EPOCH = 21
DABE_PU_STATIC_AFTER = 0.30
DABE_PU_TEACHER_AFTER = 0.70

TEACHER_CONF_FG_THRESH = 0.75
TEACHER_CONF_BG_THRESH = 0.25
TEACHER_CONF_WEIGHT_MIN = 0.0
TEACHER_CONF_WEIGHT_MAX = 1.0
TEACHER_CONF_IGNORE_PU_CORE = True

DABE_PU_WEIGHTED_BCE_EPS = 1e-6
LAMBDA_DABE_PU_STATIC = 1.0
LAMBDA_TEACHER_CONF = 1.0

USE_PROTO_CONTRAST = False
LAMBDA_PROTO_MAX = 0.0
USE_MULTI_VIEW_FEATURE = False
MULTI_VIEW_TYPES = []
USE_VIEW_CONSISTENCY = False
LAMBDA_VIEW_MAX = 0.0
GKD_MODE = "off"
USE_GKD_LITE = False
USE_TADR_ROUTER = False
