from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_long30_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_long35_lrfloor_2e5"

MAX_EPOCH = 35
max_epoch = 35

# Keep optimizer/LR policy identical to Long30 / ESA-Asym.
DINO = dict(DINO)
DINO["lr"] = 0.0006
LR = 0.0006
LR_POLICY = "step_floor"
USE_LR_FLOOR = True
LR_FLOOR = 2e-5
LR_LINEAR_STAGE1_EPOCHS = 19
LR_LINEAR_STAGE2_EPOCHS = 0
LR_FLOOR_MODE = "global"
LR_FLOOR_APPLY_AFTER_SCHEDULER_STEP = True
LR_FLOOR_APPLY_AFTER_FINETUNE_RESET = True

# Keep the DESPL-style reset aligned with Long30.
FINETUNE_RESET_EPOCH = 20
FINETUNE_RESET_TIMING = "after_epoch"
FINETUNE_RESET_REBUILD_OPTIMIZER = True
FINETUNE_RESET_REBUILD_SCHEDULER = True
FINETUNE_RESET_GLOBAL_STEP = True
FINETUNE_RESET_TEACHER = True
FINETUNE_RESET_FORCE_LR_FLOOR = True
FINETUNE_RESET_LR = 2e-5

# Keep DABE-PU static/teacher schedule fixed to epoch1-20, then teacher-only.
TEACHER_FUSION_MODE = "dabe_pu_despl_sched"
FUSION_ORIG_DECAY_EPOCHS = 20
FUSION_HOLD_FIXED_WEIGHT = 0.05
TEACHER_FUSION_PRE_RESET_EPOCHS = 19
FUSION_MIN_FIXED_WEIGHT = 0.05
TEACHER_FUSION_MAX_WEIGHT = 1.0

DABE_PU_DESPL_STAGE_START = 1
DABE_PU_DESPL_STAGE_END = 20
DABE_PU_DESPL_STATIC_START = 1.0
DABE_PU_DESPL_STATIC_END = 0.05
DABE_PU_DESPL_TEACHER_START = 0.0
DABE_PU_DESPL_TEACHER_END = 0.95
DABE_PU_DESPL_TEACHER_ONLY_START = 21

# Keep RAST/ESA-Asym active only before the reset.
RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21

ESA_ASYM_START_EPOCH = 7
ESA_ASYM_RAMP_END_EPOCH = 15
ESA_ASYM_STOP_EPOCH = 21

RAST_POST_RESET_ENABLE = False
RAST_POST_RESET_SCALE = 0.0
RAST_POST_RESET_CONFLICT_ONLY = False
RAST_POST_RESET_USE_STATIC_LOSS = False

# Keep failed branches off.
USE_HBNS_LITE = False
HBNS_LAMBDA_MAX = 0.0

USE_EPR_POS = False
EPR_LAMBDA_MAX = 0.0

# Save every epoch for this long training run.
SAVE_EVERY_EPOCH = True
SAVE_INTERVAL = 1
