from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_long50_lrfloor_2e5_sw_ones_noecst_linear30 import *  # noqa: F401,F403


EXP_NAME = (
    "dinov1_s8_dabepu_v11_pssf_h3_dagp_uncgate_ndr_"
    "long50_lrfloor_2e5"
)

MAX_EPOCH = 50
max_epoch = 50

SUPERVISION_MODE = "pssf_state"
TEACHER_FUSION_MODE = "pssf_state"

USE_PSSF = True
PSSF_VERSION = "online_innovation_retention_v1"
PSSF_SOURCE_CONFIG = (
    "configs/"
    "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_"
    "long50_lrfloor_2e5_sw_ones_noecst_linear30.py"
)

STATIC_WEIGHT_MODE = "ones"
USE_ECST = False
TEACHER_ROUTING_MODE = "none"

USE_DABE_PU = True
DABE_PU_VERSION = "pu_v11"
DABE_PU_STATIC_TARGET_MODE = "soft"
USE_DABE_PU_DESPL_SCHEDULE = False
USE_DABE_PU_STATIC_LOSS = False

PSSF_PATCH_SIZE = 37
PSSF_LOSS_SIZE = 68
PSSF_HORIZON = 3
PSSF_HISTORY_WINDOW = 3
PSSF_EPS = 1e-6
PSSF_INIT_GAIN = 0.01
PSSF_GAIN_UPSAMPLE_MODE = "bilinear"
PSSF_FEATURE_PROJ_DIM = 32
PSSF_HIDDEN_DIM = 32
PSSF_GN_GROUPS = 4
PSSF_STATE_CHANNELS = 9

PSSF_LR = 1e-3
PSSF_WEIGHT_DECAY = 1e-4
PSSF_STATE_DTYPE = "float16"
PSSF_HISTORY_DTYPE = "float16"

PSSF_TEACHER_OBSERVATION = "binary_68"
PSSF_RETENTION_TARGET = "future_binary_center"
PSSF_AUDIT_VAL_RATIO = 0.10
PSSF_AUDIT_SPLIT_SEED = 2027
PSSF_EXPECTED_TRAIN_SAMPLES = 4040

PSSF_KEEP_STATE_ACROSS_RESET = True
PSSF_CLEAR_HISTORY_AFTER_RESET = True
PSSF_RESET_NETWORK_AFTER_FINETUNE_RESET = False
PSSF_RESET_OPTIMIZER_AFTER_FINETUNE_RESET = False

PSSF_RUNTIME_FILENAME = "pssf_runtime_latest.pt"
PSSF_VIS_INTERVAL = 5
PSSF_VIS_SEED = 2027
PSSF_VIS_CAMO_COUNT = 4
PSSF_VIS_COD10K_COUNT = 8
PSSF_PATCH_NOT_BETTER_PATIENCE = 5
PSSF_TEACHER_TAKEOVER_GAIN = 0.98
PSSF_STATIC_FREEZE_GAIN = 0.005
PSSF_SPATIAL_COLLAPSE_STD = 1e-3
PSSF_GAIN_COLLAPSE_PATIENCE = 3
PSSF_SPATIAL_COLLAPSE_PATIENCE = 5
PSSF_SEG_COLLAPSE_AREA = 0.01
PSSF_SEG_COLLAPSE_PATIENCE = 3

USE_RAST = False
USE_ESA_ASYM = False
ESA_POST_RESET_ENABLE = False
USE_TEPR_LITE = False
USE_SOURCE_ARBITER = False
USE_EGSA = False
USE_TADR_ROUTER = False
USE_TCE = False
USE_LCEG = False
USE_HBNS_LITE = False
USE_EPR_POS = False
USE_PROTO_CONTRAST = False
USE_MULTI_VIEW_FEATURE = False
USE_VIEW_CONSISTENCY = False
GKD_MODE = "off"
USE_GKD_LITE = False

USE_DABE_OEM = False
USE_DABE_PU_GROUP_BALANCED_STATIC = False
USE_DABE_AWARE_LOSS = False
USE_DABE_TVERSKY_LOSS = False
USE_DABE_AREA_GUARD = False
USE_DARE = False
USE_CSSD = False
USE_HR_BFR = False
USE_CSD_DECODER = False
USE_CSD_V1R = False
USE_CACD = False
USE_PA_DAGP = False
USE_QRA = False
USE_CCR = False
USE_DREPP = False
USE_DESPL_PSEUDO = False
USE_DABE_PSEUDO = False
USE_MULTI_LEVEL_FEATURE = False
