from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_v2a_rast_v12_esa_asym_long45_lceg_v1_cc_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_v2b_rast_v12_esa_asym_long45_lceg_v1_cc_lrfloor_2e5"

# Lock the inherited Long45-CC protocol.
MAX_EPOCH = 45
max_epoch = 45

SAVE_EVERY_EPOCH = True
SAVE_EPOCH_CKPT = True
CKPT_SAVE_EVERY_EPOCH = True
SAVE_ALL_EPOCHS = True
SAVE_INTERVAL = 1

DINO = dict(DINO)
DINO["lr"] = 0.0006
LR = 0.0006
lr = 0.0006
lr0 = 0.0006
LR_POLICY = "step_floor"
lr_policy = "step_floor"
USE_LR_FLOOR = True
use_lr_floor = True
LR_FLOOR = 2e-5
lr_floor = 2e-5
LR_LINEAR_STAGE1_EPOCHS = 19
LR_LINEAR_STAGE2_EPOCHS = 0
LR_FLOOR_MODE = "global"
LR_FLOOR_APPLY_AFTER_SCHEDULER_STEP = True
LR_FLOOR_APPLY_AFTER_FINETUNE_RESET = True

FINETUNE_RESET_EPOCH = 20
FINETUNE_RESET_TIMING = "after_epoch"
FINETUNE_RESET_REBUILD_OPTIMIZER = True
FINETUNE_RESET_REBUILD_SCHEDULER = True
FINETUNE_RESET_GLOBAL_STEP = True
FINETUNE_RESET_TEACHER = True
FINETUNE_RESET_FORCE_LR_FLOOR = True
FINETUNE_RESET_LR = 2e-5

TEACHER_FUSION_MODE = "dabe_pu_despl_sched"
P_INIT_MODE = "dabe_pu_v11_desplsched"
USE_DABE_PU = True
DABE_PU_VERSION = "pu_v11"
DABE_PU_ROOT = "../datasets/cache/dabe_pu_v11_pseudo_cache/dinov1-s8"
USE_DESPL_PSEUDO = False
USE_DESPL_LIGHT_CACHE = False
USE_DESPL_PAPER_CACHE = False
USE_FIXED_IN_PSEUDO = False

DABE_PU_DESPL_STAGE_START = 1
DABE_PU_DESPL_STAGE_END = 20
DABE_PU_DESPL_STATIC_START = 1.0
DABE_PU_DESPL_STATIC_END = 0.05
DABE_PU_DESPL_TEACHER_START = 0.0
DABE_PU_DESPL_TEACHER_END = 0.95
DABE_PU_DESPL_TEACHER_ONLY_START = 21
USE_TEACHER_BINARY_FULL_LOSS = True
USE_TEACHER_SOFT_FULL_LOSS = False
TEACHER_TARGET_MODE = "binary"
DABE_PU_STATIC_TARGET_MODE = "soft"

USE_RAST = True
RAST_VERSION = "v1.2_esa_asym_ndr_v2b"
RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21
RAST_POST_RESET_ENABLE = False
RAST_POST_RESET_SCALE = 0.0
RAST_POST_RESET_CONFLICT_ONLY = False
RAST_POST_RESET_USE_STATIC_LOSS = False

USE_ESA_ASYM = True
ESA_ASYM_START_EPOCH = 7
ESA_ASYM_RAMP_END_EPOCH = 15
ESA_ASYM_STOP_EPOCH = 21
USE_ESA_DIAGNOSTIC = True

USE_LCEG = True
LCEG_VERSION = "v1_late_core_extent_guard_cc45_ndr_v2b"
LCEG_START_EPOCH = 26
LCEG_RAMP_END_EPOCH = 28
LCEG_STOP_EPOCH = 36
LCEG_COVER_CACHE_ROOT = "../datasets/cache/lceg_cover_cache/dinov1-s8/long35_epoch025"
LCEG_COVER_MODEL = "student"
LCEG_COVER_EPOCH = 25
USE_CLEAN_CONSOLIDATION_LOG = True

# Keep non-target branches off.
USE_TCE = False
TCE_LAMBDA_MAX = 0.0
USE_HBNS_LITE = False
HBNS_LAMBDA_MAX = 0.0
USE_EPR_POS = False
EPR_LAMBDA_MAX = 0.0
USE_DARE = False
USE_PROTO_CONTRAST = False
LAMBDA_PROTO_MAX = 0.0
USE_TADR_ROUTER = False
USE_DABE_AWARE_LOSS = False
USE_DABE_TVERSKY_LOSS = False
USE_DABE_AREA_GUARD = False
GKD_MODE = "off"
USE_GKD_LITE = False
USE_TADR_ROUTER = False

# NDR-v2b: keep v2a shape-aware gate, add clean-stage shape lower-bound and bg locks.
USE_NDR_BRANCH = True
USE_NDR_V2 = True
NDR_VERSION = "v2b_shape_lb_bg_prob_lock"

NDR_V2_USE_SHAPE_GATE = True
NDR_V2_SHAPE_GATE_MODE = "soft_boundary_edge_boost"
NDR_V2_BOUNDARY_SOURCE = "coarse_prob"
NDR_V2_BOUNDARY_RADIUS = 2
NDR_V2_BOUNDARY_DETACH = True
NDR_V2_BOUNDARY_SOFT = True
NDR_V2_SHAPE_ALPHA_MAX = 0.20
NDR_V2_SHAPE_EDGE_MIX = 0.50
NDR_V2_SHAPE_UNCERT_MIX = 0.50
NDR_V2_GATE_COMBINE = "add_clamp"

NDR_V2_USE_SHAPE_LOWER_BOUND = True
NDR_V2_SHAPE_LOWER_BOUND_WEIGHT = 0.0
NDR_V2_SHAPE_LB_START_EPOCH = 36
NDR_V2_SHAPE_LB_RAMP_END_EPOCH = 38
NDR_V2_SHAPE_LB_STOP_EPOCH = 46
NDR_V2_SHAPE_LB_WEIGHT_MAX = 0.003
NDR_V2_SHAPE_LB_FLOOR = 0.35
NDR_V2_SHAPE_LB_WEIGHTED_NORMALIZE = True
NDR_V2_SHAPE_LB_MAX_RATIO_PER_IMAGE = 0.005
NDR_V2_SHAPE_LB_MIN_PIXELS_PER_IMAGE = 4
NDR_V2_SHAPE_LB_BOUNDARY_THRESH = 0.05
NDR_V2_SHAPE_LB_USE_EDGE = True
NDR_V2_SHAPE_LB_EDGE_Q = 0.60
NDR_V2_SHAPE_LB_USE_DINO_MARGIN = True
NDR_V2_SHAPE_LB_FEATURE_SIZE = 37
NDR_V2_SHAPE_LB_MARGIN_THRESH = 0.0
NDR_V2_SHAPE_LB_DETACH_PROTO = True
NDR_V2_SHAPE_LB_USE_NEAR_FG = True
NDR_V2_SHAPE_LB_NEAR_RADIUS = 3
NDR_V2_SHAPE_LB_NEAR_PROB_THRESH = 0.45
NDR_V2_SHAPE_LB_USE_EXTENT = True
NDR_V2_SHAPE_LB_USE_UNKNOWN = False
NDR_V2_SHAPE_LB_EXCLUDE_BG_CORE = True
NDR_V2_SHAPE_LB_REQUIRE_TEACHER_BG = True
NDR_V2_SHAPE_LB_DETACH_MASK = True

NDR_V2_USE_BG_RES_LOCK = True
NDR_V2_BG_RES_LOCK_START_EPOCH = 36
NDR_V2_BG_RES_LOCK_RAMP_END_EPOCH = 38
NDR_V2_BG_RES_LOCK_STOP_EPOCH = 46
NDR_V2_BG_RES_LOCK_WEIGHT_MAX = 0.020
NDR_V2_BG_LOCK_WEIGHT = 0.020

NDR_V2_USE_BG_PROB_LOCK = True
NDR_V2_BG_PROB_LOCK_START_EPOCH = 36
NDR_V2_BG_PROB_LOCK_RAMP_END_EPOCH = 38
NDR_V2_BG_PROB_LOCK_STOP_EPOCH = 46
NDR_V2_BG_PROB_LOCK_WEIGHT_MAX = 0.010
NDR_V2_BG_PROB_LOCK_DELTA = 0.02

NDR_V2_BG_CORE_THRESH = 0.5
NDR_V2_BG_LOCK_USE_BG_CORE = True
NDR_V2_BG_LOCK_USE_LOW_TARGET_BG = True
NDR_V2_LOW_TARGET_THRESH = 0.15
NDR_V2_LOW_TARGET_WEIGHT_THRESH = 0.50
NDR_V2_BG_LOCK_DETACH_MASK = True
NDR_V2_BG_LOCK_EPS = 1e-6

USE_NDR_V2_DIAGNOSTIC = True
NDR_V2_DIAG_LOG_INTERVAL_EPOCH = 1
