from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_relaxamb_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_epr_pos_lrfloor_2e5"

USE_RAST = True
RAST_VERSION = "v1.2_epr_pos"

RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21

RAST_CONFLICT_TEACHER_MULT = 0.20
RAST_EXTENT_TEACHER_MULT = 1.00
RAST_UNKNOWN_TEACHER_MULT = 0.50
RAST_OTHER_TEACHER_MULT = 1.00

RAST_POST_RESET_ENABLE = False
RAST_POST_RESET_SCALE = 0.00
RAST_POST_RESET_CONFLICT_ONLY = False
RAST_POST_RESET_USE_STATIC_LOSS = False

RAST_APPLY_TO_FINAL = True
RAST_APPLY_TO_COARSE_AUX = True
RAST_APPLY_TO_BASE_AUX = True
RAST_WEIGHTED_LOSS_NORMALIZE = True

USE_HBNS_LITE = False
HBNS_LAMBDA_MAX = 0.0

USE_EPR_POS = True
EPR_VERSION = "pos_lite_v1"

EPR_START_EPOCH = 7
EPR_RAMP_END_EPOCH = 15
EPR_STOP_EPOCH = 21

EPR_LAMBDA_MAX = 0.005

EPR_APPLY_TO_FINAL = True
EPR_APPLY_TO_COARSE_AUX = True
EPR_APPLY_TO_BASE_AUX = False

EPR_REGION = "extent"
EPR_USE_UNKNOWN = False
EPR_POSITIVE_ONLY = True

EPR_REQUIRE_TEACHER_FG = True
EPR_TEACHER_CONF_THRESH = 0.75

EPR_USE_DINO_PROTO_MARGIN = True
EPR_MARGIN_THRESH = 0.05

EPR_MAX_RATIO_PER_IMAGE = 0.03
EPR_MIN_PIXELS_PER_IMAGE = 8

EPR_FEATURE_SOURCE = "cached_dino"
EPR_FEATURE_SIZE = 37
EPR_LOSS_SIZE = 68

EPR_DETACH_MASK = True
EPR_DETACH_PROTO = True
EPR_WEIGHTED_NORMALIZE = True

USE_EPR_DIAGNOSTIC = True
USE_ESA_DIAGNOSTIC = True
ESA_DIAG_LOG_INTERVAL_EPOCH = 1
