from configs.dinov1_s8_dabepu_v11_dagp_uncgate_csd_v1r_rast_v12_esa_asym_clean35_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_csd_v1r_cssd_v1a_rast_v12_esa_asym_clean35_lrfloor_2e5"

MAX_EPOCH = 35
max_epoch = 35
SAVE_EVERY_EPOCH = True
SAVE_INTERVAL = 1

# CSSD-v1a uses one final-layer attention-key feature source at two input scales.
USE_CSSD = True
CSSD_VERSION = "v1a_final_layer_cross_scale_distill"
CSSD_TRAIN_ONLY = True
CSSD_USE_SHARED_MODEL = True
CSSD_USE_SEPARATE_HR_HEAD = False

CSSD_NORMAL_INPUT_SIZE = 296
CSSD_NORMAL_FEATURE_SIZE = 37
CSSD_HR_INPUT_SIZE = 384
CSSD_HR_FEATURE_SIZE = 48
CSSD_HR_FEATURE_CHANNELS = 384
CSSD_HR_CACHE_ROOT = "../datasets/cache/features_cache_cssd/dinov1-s8/input384"
CSSD_HR_CACHE_DTYPE = "float32"
CSSD_HR_CACHE_KEY = "feature"
CSSD_HR_FEATURE_FIELD = "feature_cssd_hr"

CSSD_WARMUP_EPOCH = 6
CSSD_START_EPOCH = 7
CSSD_RAMP_END_EPOCH = 15
CSSD_STOP_EPOCH = 36

CSSD_USE_HR_SUPERVISED_LOSS = True
CSSD_HR_SUP_WEIGHT_MAX = 0.25
CSSD_HR_SUP_USE_ORIGINAL_PIPELINE = True
CSSD_HR_SUP_APPLY_TO_FINAL = True
CSSD_HR_SUP_APPLY_TO_COARSE = True
CSSD_HR_SUP_APPLY_TO_BASE = True

CSSD_USE_PRED_DISTILL = True
CSSD_PRED_WEIGHT_MAX = 0.05
CSSD_CORE_LOSS_MULT = 0.25
CSSD_TRANSFER_LOSS_MULT = 1.00
CSSD_CORE_CONF_THRESH = 0.60
CSSD_TRANSFER_CONF_THRESH = 0.70
CSSD_CONF_ADV_MARGIN = 0.05
CSSD_MIN_PROB_DIFF = 0.05
CSSD_TRANSFER_REGION = "extent"
CSSD_USE_UNKNOWN = False
CSSD_TRANSFER_MAX_RATIO_PER_IMAGE = 0.03
CSSD_TRANSFER_MIN_PIXELS_PER_IMAGE = 4
CSSD_EXCLUDE_FG_BG_CONFLICT = True
CSSD_DETACH_HR_TARGET = True

CSSD_USE_BOUNDARY_CONSISTENCY = True
CSSD_BOUNDARY_WEIGHT_MAX = 0.02
CSSD_BOUNDARY_TEACHER_Q = 0.70
CSSD_BOUNDARY_IMAGE_EDGE_Q = 0.50
CSSD_BOUNDARY_MAX_RATIO_PER_IMAGE = 0.10
CSSD_BOUNDARY_MIN_PIXELS_PER_IMAGE = 8
CSSD_BOUNDARY_USE_SOFT_GRADIENT = True
CSSD_BOUNDARY_USE_HARD_CONTOUR = False

CSSD_HR_MICROBATCH = 4
CSSD_HR_FORWARD_EVERY = 1
CSSD_SKIP_HR_FORWARD_WHEN_SCALE_ZERO = True

USE_CSSD_DIAGNOSTIC = True
CSSD_DIAG_LOG_INTERVAL_EPOCH = 1
CSSD_STRICT_CACHE_CHECK = True
CSSD_STRICT_SINGLE_VIEW_EVAL = True

# Lock the baseline architecture and training protocol.
HEAD_TYPE = "dagp_safe_csd_v1r"
head_type = "dagp_safe_csd_v1r"
USE_DAGP_SAFE_HEAD = True
USE_CSD_V1R = True
USE_NDR_BRANCH = False
USE_NDR_V2 = False
USE_HR_BFR = False
USE_LCEG = False
LCEG_LAMBDA_MAX = 0.0
USE_TCE = False
TCE_LAMBDA_MAX = 0.0
USE_HBNS_LITE = False
HBNS_LAMBDA_MAX = 0.0
USE_EPR_POS = False
EPR_LAMBDA_MAX = 0.0
USE_DARE = False
USE_PROTO_CONTRAST = False
LAMBDA_PROTO_MAX = 0.0
USE_MULTI_VIEW_FEATURE = False
use_multi_view_feature = False
USE_VIEW_CONSISTENCY = False
use_view_consistency = False
GKD_MODE = "off"
USE_GKD_LITE = False
USE_TADR_ROUTER = False

# Explicitly preserve batch, optimizer/reset, DABE-PU, RAST, and ESA behavior.
BATCH_SIZE = 16
DINO = dict(DINO)
DINO["lr"] = 0.0006
LR = 0.0006
LR_POLICY = "step_floor"
USE_LR_FLOOR = True
LR_FLOOR = 2e-5
FINETUNE_RESET_EPOCH = 20
FINETUNE_RESET_TIMING = "after_epoch"
FINETUNE_RESET_REBUILD_OPTIMIZER = True
FINETUNE_RESET_REBUILD_SCHEDULER = True
FINETUNE_RESET_GLOBAL_STEP = True
FINETUNE_RESET_TEACHER = True
FINETUNE_RESET_FORCE_LR_FLOOR = True
FINETUNE_RESET_LR = 2e-5

USE_DABE_PU = True
DABE_PU_VERSION = "pu_v11"
P_INIT_MODE = "dabe_pu_v11_desplsched"
TEACHER_FUSION_MODE = "dabe_pu_despl_sched"
USE_TEACHER_BINARY_FULL_LOSS = True
USE_TEACHER_SOFT_FULL_LOSS = False
TEACHER_TARGET_MODE = "binary"
DABE_PU_STATIC_TARGET_MODE = "soft"

RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21
RAST_POST_RESET_ENABLE = False
USE_ESA_ASYM = True
ESA_ASYM_START_EPOCH = 7
ESA_ASYM_RAMP_END_EPOCH = 15
ESA_ASYM_STOP_EPOCH = 21
