from configs.dinov1_s8_dabepu_v11_egsa_r2b_signaware_dagp_uncgate_ndr_stage20_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = (
    "dinov1_s8_dabepu_v11_egsa_r2b_signaware_dagp_uncgate_ndr_"
    "long45_lrfloor_2e5"
)
MAX_EPOCH = 45
max_epoch = 45
SAVE_EVERY_EPOCH = True
SAVE_INTERVAL = 1

SOURCE_ARBITER_STAGE = "long45"
SOURCE_ARBITER_RESUME_ONLY = True
SOURCE_ARBITER_REQUIRED_RESUME_EPOCH = 6
SOURCE_ARBITER_SKIP_AFTER_EPOCH_RESET = False

# Full Audit v2 is not a strict pass. This exploratory run allows only the two
# observed positive-branch concentration failures and no other failure.
SOURCE_ARBITER_TARGET_AUDIT_REQUIRE_PASS = False
SOURCE_ARBITER_AUDIT_CONCENTRATION_OVERRIDE = True
SOURCE_ARBITER_AUDIT_ALLOWED_FAILURES = [
    "positive:top_1_percent_images_minority_share",
    "positive:top_10_percent_images_minority_share",
]
SOURCE_ARBITER_EXPLORATORY_STAGE45 = True

# Fixed full-audit initialization. No per-batch inverse-frequency recompute.
SOURCE_ARBITER_POS_TEACHER_CLASS_WEIGHT = 3.4297335021
SOURCE_ARBITER_POS_DABE_CLASS_WEIGHT = 0.7226316013
SOURCE_ARBITER_NEG_TEACHER_CLASS_WEIGHT = 3.7554045924
SOURCE_ARBITER_NEG_DABE_CLASS_WEIGHT = 0.7199848699
SOURCE_ARBITER_UTILITY_CLASS_WEIGHT_EPOCH_EMA = False

# Only these catastrophic conditions may terminate the exploratory run.
SOURCE_ARBITER_USE_EXPLORATORY_STAGE45_STOP_RULES = True
SOURCE_ARBITER_STOP_RESIDUAL_SATURATION_MAX = 0.60
SOURCE_ARBITER_STOP_RESIDUAL_SATURATION_PATIENCE = 2
SOURCE_ARBITER_STOP_NEG_CONFLICT_START_EPOCH = 11
SOURCE_ARBITER_STOP_NEG_CONFLICT_PATIENCE = 2
SOURCE_ARBITER_STOP_AREA_MAX_EPOCH10 = 0.135
SOURCE_ARBITER_STOP_AREA_MAX_EPOCH20 = 0.115
SOURCE_ARBITER_STOP_AREA_POST_RESET = 0.105
SOURCE_ARBITER_POST_RESET_MIN_EPOCH20_AREA_RATIO = 0.90
SOURCE_ARBITER_POST_RESET_AREA_PATIENCE = 3
SOURCE_ARBITER_STOP_AREA_CEILING = 0.190
SOURCE_ARBITER_STOP_AREA_CEILING_PATIENCE = 2
