from configs.dinov1_s8_despl_only_lr_floor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_only_dagp_safe_lrfloor_2e5"

HEAD_TYPE = "dagp_safe"
USE_DAGP_HEAD = False
USE_DAGP_SAFE_HEAD = True

USE_LR_FLOOR = True
LR_FLOOR = 2e-5
LR_POLICY = "step_floor"

DAGP_SAFE_HIDDEN = 64
DAGP_SAFE_TOPK = 12
DAGP_SAFE_TAU = 0.07

DAGP_SAFE_ALPHA_MAX = 0.05
DAGP_SAFE_GAMMA_MAX = 0.03
DAGP_SAFE_WARMUP_EPOCH = 6
DAGP_SAFE_RAMP_START_EPOCH = 7
DAGP_SAFE_RAMP_END_EPOCH = 15

DAGP_SAFE_AFFINITY_DETACH = True
DAGP_SAFE_EXCLUDE_SELF = True

DAGP_SAFE_USE_PROB_GATE = True
DAGP_SAFE_PROB_GATE_SIGMA = 0.25
DAGP_SAFE_PROB_GATE_EPS = 1e-6

DAGP_SAFE_ZERO_INIT_GRAPH_PRED = True
DAGP_SAFE_ZERO_INIT_VALUE = False

USE_BASE_AUX_LOSS = True
LAMBDA_BASE_AUX = 0.5
LAMBDA_BASE_AUX_AFTER_RESET = 0.3
BASE_AUX_NORMALIZE = True

DAGP_SAFE_DEBUG_FIRST_BATCH = True
