from configs.dinov1_s8_dabepu_v11_ecst_dagp_uncgate_ndr_long45_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_ecst_egsa_r1_dagp_uncgate_ndr_long45_lrfloor_2e5"

# Evidence-Guided Source Arbitration R1.
USE_SOURCE_ARBITER = True
SOURCE_ARBITER_VERSION = "egsa_r1_delayed_cv_v1"
SOURCE_ARBITER_MODE = "residual_over_ecst"

SOURCE_ARBITER_START_EPOCH = 7
SOURCE_ARBITER_RAMP_END_EPOCH = 15
SOURCE_ARBITER_STOP_EPOCH = 21

SOURCE_ARBITER_INPUT_CHANNELS = 18
SOURCE_ARBITER_HIDDEN_1 = 32
SOURCE_ARBITER_HIDDEN_2 = 32
SOURCE_ARBITER_HIDDEN_3 = 16
SOURCE_ARBITER_DILATION = 2
SOURCE_ARBITER_RESIDUAL_BOUND = 1.5
SOURCE_ARBITER_ZERO_INIT_HEAD = True

SOURCE_ARBITER_DETACH_INPUTS = True
SOURCE_ARBITER_DETACH_GATE_FOR_SEG = True
SOURCE_ARBITER_SHARE_GATE_ACROSS_BRANCHES = True
SOURCE_ARBITER_USE_ECST_TEACHER_MAP = True
SOURCE_ARBITER_PRIOR_EPS = 1e-4
SOURCE_ARBITER_USE_DISAGREEMENT_SCALE = True
SOURCE_ARBITER_DISAGREEMENT_DENOM = 0.5
SOURCE_ARBITER_DINO_MARGIN_TAU = 0.05
SOURCE_ARBITER_DABE_WEIGHT_INPUT_MODE = "raw_clamped"
SOURCE_ARBITER_DABE_WEIGHT_FIXED_SCALE = 1.0

SOURCE_ARBITER_MEMORY_UPDATE_START_EPOCH = 1
SOURCE_ARBITER_MEMORY_UPDATE_END_EPOCH = 20
SOURCE_ARBITER_MEMORY_DTYPE = "float16"
SOURCE_ARBITER_MIN_MEMORY_AGE_EPOCH = 1
SOURCE_ARBITER_MAX_MEMORY_AGE_EPOCH = 2
SOURCE_ARBITER_SAVE_MEMORY = True

SOURCE_ARBITER_USE_UTILITY_EVALUATOR = True
SOURCE_ARBITER_UTILITY_EMA_DECAY = 0.999
SOURCE_ARBITER_UTILITY_USE_HFLIP = True
SOURCE_ARBITER_UTILITY_INTERVAL = 1
SOURCE_ARBITER_SAVE_UTILITY_EVALUATOR = True
HFLIP_FEATURE_CACHE_ROOT = "../datasets/cache/features_cache_hflip"
HFLIP_FEATURE_PREFLIGHT_SAMPLES = 4040

SOURCE_ARBITER_UTILITY_TAU = 0.10
SOURCE_ARBITER_UTILITY_MIN_CONSENSUS_CONF = 0.30
SOURCE_ARBITER_UTILITY_MAX_VIEW_DIFF = 0.15
SOURCE_ARBITER_UTILITY_MIN_SOURCE_DISAGREEMENT = 0.15
SOURCE_ARBITER_UTILITY_MIN_HISTORY = 3
SOURCE_ARBITER_UTILITY_VIEW_TAU = 0.05
SOURCE_ARBITER_UTILITY_GAP_SCALE = 0.10

SOURCE_ARBITER_LAMBDA_UTILITY = 1.0
SOURCE_ARBITER_LAMBDA_PRIOR = 0.10
SOURCE_ARBITER_LAMBDA_MASS = 0.05
SOURCE_ARBITER_LAMBDA_SMOOTH = 0.005
SOURCE_ARBITER_MASS_TOLERANCE = 0.20
SOURCE_ARBITER_SMOOTH_KAPPA = 5.0

SOURCE_ARBITER_LR = 1e-4
SOURCE_ARBITER_WEIGHT_DECAY = 1e-4
SOURCE_ARBITER_BETA1 = 0.9
SOURCE_ARBITER_BETA2 = 0.999
SOURCE_ARBITER_GRAD_CLIP = 1.0

SOURCE_ARBITER_DEBUG_FIRST_BATCH = True
SOURCE_ARBITER_LOG_INTERVAL_EPOCH = 1
SOURCE_ARBITER_SAVE_GATE_VIS = True
SOURCE_ARBITER_GATE_VIS_COUNT = 8
SOURCE_ARBITER_VALIDATION_MODULUS = 10

# EGSA is isolated from every historical routing/mining/decoder experiment.
USE_RAST = False
USE_ESA_ASYM = False
ESA_POST_RESET_ENABLE = False
USE_TEPR_LITE = False
USE_ESA_BER = False
USE_HBNS_LITE = False
USE_EPR_POS = False
USE_TCE = False
USE_LCEG = False
USE_CSSD = False
USE_PA_DAGP = False
USE_CSD_DECODER = False
USE_CSD_V1R = False
USE_CACD = False
USE_HR_BFR = False
USE_NDR_V2 = False
USE_TADR_ROUTER = False
USE_PROTO_CONTRAST = False
USE_MULTI_VIEW_FEATURE = False
USE_VIEW_CONSISTENCY = False
