from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_puconf_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_oem_dagp_uncgate_ndr_lrfloor_2e5"

USE_DABE_PU = True
DABE_PU_VERSION = "pu_v11"
DABE_PU_ROOT = "../datasets/cache/dabe_pu_v11_pseudo_cache/dinov1-s8"
P_INIT_MODE = "dabe_pu_v11_oem"

USE_DESPL_PSEUDO = False
USE_DESPL_LIGHT_CACHE = False
USE_DESPL_PAPER_CACHE = False
USE_FIXED_IN_PSEUDO = False
use_despl_pseudo = False
use_despl_light_cache = False
use_despl_paper_cache = False
use_fixed_in_pseudo = False
fixed_used_for_training = False

TEACHER_FUSION_MODE = "dabe_pu_oem"
USE_DABE_OEM = True
USE_DABE_PU_SEED_STATIC_LOSS = True
USE_DABE_OEM_DYNAMIC_EXTENT = True

USE_DABE_PU_STATIC_LOSS = False
USE_DABE_PU_GROUP_BALANCED_STATIC = False
USE_TEACHER_CONF_LOSS = False
USE_TEACHER_CONF_BALANCED = False

FINETUNE_RESET_EPOCH = -1
FINETUNE_RESET_REBUILD_OPTIMIZER = False
FINETUNE_RESET_REBUILD_SCHEDULER = False
FINETUNE_RESET_GLOBAL_STEP = False
FINETUNE_RESET_TEACHER = False

MAX_EPOCH = 25
USE_LR_FLOOR = True
LR_FLOOR = 2e-5
EMA_WEIGHT = 0.99

OEM_SEED_LAMBDA_FG = 1.00
OEM_SEED_LAMBDA_BG = 1.00
OEM_SEED_LAMBDA_FG_FALLBACK = 0.35
OEM_SEED_GROUP_EPS = 1e-6

OEM_USE_SEED_LOSS_ON_FINAL = True
OEM_USE_SEED_LOSS_ON_COARSE = True
OEM_USE_SEED_LOSS_ON_BASE = True

OEM_STAGE1_END = 3
OEM_STAGE2_START = 4
OEM_STAGE2_END = 15
OEM_DYN_POS_STAGE2_START = 0.00
OEM_DYN_POS_STAGE2_END = 0.35
OEM_DYN_BG_STAGE2_START = 0.00
OEM_DYN_BG_STAGE2_END = 0.12
OEM_STAGE3_START = 16
OEM_DYN_POS_STAGE3 = 0.35
OEM_DYN_BG_STAGE3 = 0.12

OEM_POS_REGION = "extent"
OEM_BG_REGION = "non_fg_core"
OEM_USE_UNKNOWN_FOR_POS = False
OEM_USE_UNKNOWN_FOR_BG = True

OEM_PROTO_FEATURE_SOURCE = "dino37"
OEM_PROTO_L2_NORM = True
OEM_PROTO_MIN_FG_PIXELS = 4
OEM_PROTO_MIN_BG_PIXELS = 16

OEM_TEACHER_POS_THRESH = 0.60
OEM_TEACHER_BG_THRESH = 0.20
OEM_PROTO_POS_MIN = 0.05
OEM_PROTO_POS_QUANTILE = 0.80
OEM_PROTO_BG_MAX = -0.05
OEM_PROTO_BG_QUANTILE = 0.20

OEM_POS_CAP_RATIO = 0.05
OEM_POS_CAP_TO_FG = 0.75
OEM_POS_MIN_PIXELS = 4

OEM_BG_CAP_RATIO = 0.10
OEM_BG_TO_POS_MAX = 3.0
OEM_BG_MIN_PIXELS = 32
OEM_BG_CAP_IF_NO_POS_RATIO = 0.03

OEM_DYN_POS_TARGET_MODE = "teacher_soft"
OEM_DYN_POS_TARGET_MIN = 0.65
OEM_DYN_POS_TARGET_MAX = 0.95
OEM_DYN_BG_TARGET = 0.00

OEM_USE_DYNAMIC_ON_FINAL = True
OEM_USE_DYNAMIC_ON_COARSE = False
OEM_USE_DYNAMIC_ON_BASE = False

USE_DABE_AWARE_LOSS = False
USE_DABE_TVERSKY_LOSS = False
USE_DABE_AREA_GUARD = False
USE_PROTO_CONTRAST = False
LAMBDA_PROTO_MAX = 0.0
USE_MULTI_VIEW_FEATURE = False
MULTI_VIEW_TYPES = []
USE_VIEW_CONSISTENCY = False
LAMBDA_VIEW_MAX = 0.0
GKD_MODE = "off"
USE_GKD_LITE = False
USE_TADR_ROUTER = False
