from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_long35_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_v2_ber_long35_lrfloor_2e5"

MAX_EPOCH = 35
max_epoch = 35
SAVE_EVERY_EPOCH = True
SAVE_INTERVAL = 1

# Keep the original Long35 model and training protocol unchanged.
HEAD_TYPE = "dagp_safe"
head_type = "dagp_safe"
USE_DAGP_SAFE_HEAD = True
USE_NDR_BRANCH = True
USE_NDR_V2 = False
USE_CSD_V1R = False
USE_PA_DAGP = False

USE_DABE_PU = True
DABE_PU_VERSION = "pu_v11"

USE_RAST = True
RAST_VERSION = "v1.2_esa_v2_ber"
RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21
RAST_POST_RESET_ENABLE = False
RAST_POST_RESET_SCALE = 0.0
RAST_POST_RESET_CONFLICT_ONLY = False
RAST_POST_RESET_USE_STATIC_LOSS = False

USE_ESA_ASYM = True
ESA_ASYM_START_EPOCH = 7
ESA_ASYM_RAMP_END_EPOCH = 15
ESA_ASYM_STOP_EPOCH = 21
ESA_POST_RESET_ENABLE = False

ESA_MARGIN_FG_LIKE = 0.05
ESA_MARGIN_BG_LIKE = -0.05
ESA_EXTENT_TEACHER_BG_FG_LIKE_MULT = 0.25
ESA_EXTENT_TEACHER_BG_AMBIG_MULT = 0.50
ESA_EXTENT_TEACHER_BG_BG_LIKE_MULT = 1.00

USE_LCEG = False
USE_TCE = False
USE_HR_BFR = False
USE_CSSD = False
USE_HBNS_LITE = False
USE_EPR_POS = False
USE_PROTO_CONTRAST = False
USE_MULTI_VIEW_FEATURE = False
use_multi_view_feature = False
MULTI_VIEW_TYPES = []
multi_view_types = []
USE_TADR_ROUTER = False
GKD_MODE = "off"
USE_GKD_LITE = False

# ESA-v2-BER is a training-only, final-logit ranking auxiliary.
USE_ESA_BER = True
ESA_BER_VERSION = "v1_bidirectional_balanced_evidence_ranking"
ESA_BER_AFTER_RESET_ONLY = True
ESA_BER_START_EPOCH = 21
ESA_BER_RAMP_END_EPOCH = 23
ESA_BER_STOP_EPOCH = 36

ESA_BER_LAMBDA_MAX = 0.005
ESA_BER_RANK_MARGIN = 0.20
ESA_BER_RANK_TAU = 0.10

ESA_BER_APPLY_TO_FINAL_ONLY = True
ESA_BER_APPLY_TO_COARSE = False
ESA_BER_APPLY_TO_BASE = False

ESA_BER_DETACH_CANDIDATES = True
ESA_BER_DETACH_TEACHER = True
ESA_BER_DETACH_GRAPH_EVIDENCE = True
ESA_BER_DETACH_MARGIN = True

ESA_BER_MIN_PAIRS_PER_IMAGE = 4
ESA_BER_MAX_PAIRS_PER_IMAGE = 24
ESA_BER_MAX_RATIO_PER_CLASS = 0.005

ESA_BER_POS_REGION = "extent"
ESA_BER_POS_REQUIRE_TEACHER_BG = True
ESA_BER_POS_MARGIN_MIN = 0.05
ESA_BER_POS_CONN_MIN = 0.05
ESA_BER_POS_CONN_SUPPORT_MIN = 0.05
ESA_BER_POS_STUDENT_PROB_MIN = 0.15
ESA_BER_POS_EXCLUDE_FG_CORE = True
ESA_BER_POS_EXCLUDE_BG_CORE = True
ESA_BER_POS_EXCLUDE_UNKNOWN = True

ESA_BER_USE_NEG_EXTENT = True
ESA_BER_NEG_EXTENT_MARGIN_MIN = -0.05
ESA_BER_NEG_EXTENT_CONN_MAX = -0.05
ESA_BER_NEG_EXTENT_CONN_SUPPORT_MIN = 0.05
ESA_BER_NEG_EXTENT_STUDENT_PROB_MIN = 0.15
ESA_BER_NEG_EXTENT_REQUIRE_TEACHER_BG = True

ESA_BER_USE_NEG_HARD_BG = True
ESA_BER_NEG_HARD_BG_MARGIN_MAX = -0.05
ESA_BER_NEG_HARD_BG_CONN_MAX = -0.05
ESA_BER_NEG_HARD_BG_CONN_SUPPORT_MIN = 0.05
ESA_BER_NEG_HARD_BG_STUDENT_PROB_MIN = 0.30
ESA_BER_NEG_HARD_BG_ALLOW_TEACHER_FG = True
ESA_BER_LOW_TARGET_THRESH = 0.15
ESA_BER_LOW_TARGET_WEIGHT_THRESH = 0.50
ESA_BER_NEG_HARD_BG_USE_BG_CORE = True
ESA_BER_NEG_HARD_BG_USE_LOW_TARGET_BG = True

ESA_BER_POS_SCORE_MARGIN_WEIGHT = 0.40
ESA_BER_POS_SCORE_CONN_WEIGHT = 0.40
ESA_BER_POS_SCORE_DYNAMIC_WEIGHT = 0.20
ESA_BER_NEG_EXTENT_SCORE_TARGETLIKE_WEIGHT = 0.25
ESA_BER_NEG_EXTENT_SCORE_BG_CONN_WEIGHT = 0.45
ESA_BER_NEG_EXTENT_SCORE_HARDNESS_WEIGHT = 0.30
ESA_BER_NEG_HARD_SCORE_MARGIN_WEIGHT = 0.30
ESA_BER_NEG_HARD_SCORE_CONN_WEIGHT = 0.30
ESA_BER_NEG_HARD_SCORE_HARDNESS_WEIGHT = 0.40

DAGP_SAFE_RETURN_GRAPH_AUX_FOR_BER = True
ESA_BER_GRAPH_WEIGHT_SOURCE = "semantic_topk"

