from configs.dinov1_s8_despl_only_teacher_cache import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_only_pure_supervision"

USE_PURE_DESPL_SUPERVISION = True
PURE_DESPL_SUPERVISION_SOURCE = "p_despl"

USE_DESPL_ANCHOR_PBCE = False
ANCHOR_PBCE_LAMBDA_EARLY = 0.0
ANCHOR_PBCE_LAMBDA_LATE = 0.0

HEAD_TYPE = "simple"

USE_DESPL_PSEUDO = True
USE_DESPL_LIGHT_CACHE = True
P_INIT_MODE = "despl_only"
P_INIT_DESPL_WEIGHT = 1.0
P_INIT_FIXED_WEIGHT = 0.0

PSEUDO_USE_GCM = False
PSEUDO_USE_TEACHER = False
PSEUDO_USE_LOCAL_ATTN = False

USE_PSTA = False
USE_MNP = False
DINO_USE_LORA = False
USE_CNN_DETAIL_BRANCH = False
USE_AFF = False
USE_DUAL_FG_BG_HEAD = False
USE_BOUNDARY_HEAD = False

LAMBDA_MNP = 0.0
LAMBDA_LOCAL = 0.0
LAMBDA_PSTA = 0.0
LAMBDA_CONTRAST = 0.0
LAMBDA_BOUNDARY = 0.0
LAMBDA_ENTROPY = 0.0
LAMBDA_ANCHOR = 0.0
