from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_long35_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_long35_lceg_v1_lrfloor_2e5"

MAX_EPOCH = 35
max_epoch = 35

SAVE_EVERY_EPOCH = True
SAVE_EPOCH_CKPT = True
CKPT_SAVE_EVERY_EPOCH = True
SAVE_ALL_EPOCHS = True
SAVE_INTERVAL = 1

# Lock Long35 training protocol.
DINO = dict(DINO)
DINO["lr"] = 0.0006
LR = 0.0006
LR_POLICY = "step_floor"
USE_LR_FLOOR = True
LR_FLOOR = 2e-5
LR_LINEAR_STAGE1_EPOCHS = 19
LR_LINEAR_STAGE2_EPOCHS = 0
LR_FLOOR_MODE = "global"
LR_FLOOR_APPLY_AFTER_SCHEDULER_STEP = True
LR_FLOOR_APPLY_AFTER_FINETUNE_RESET = True

FINETUNE_RESET_EPOCH = 20
FINETUNE_RESET_TIMING = "after_epoch"
FINETUNE_RESET_REBUILD_OPTIMIZER = True
FINETUNE_RESET_REBUILD_SCHEDULER = True
FINETUNE_RESET_GLOBAL_STEP = True
FINETUNE_RESET_TEACHER = True
FINETUNE_RESET_FORCE_LR_FLOOR = True
FINETUNE_RESET_LR = 2e-5

TEACHER_FUSION_MODE = "dabe_pu_despl_sched"
DABE_PU_DESPL_STAGE_START = 1
DABE_PU_DESPL_STAGE_END = 20
DABE_PU_DESPL_STATIC_START = 1.0
DABE_PU_DESPL_STATIC_END = 0.05
DABE_PU_DESPL_TEACHER_START = 0.0
DABE_PU_DESPL_TEACHER_END = 0.95
DABE_PU_DESPL_TEACHER_ONLY_START = 21

USE_DABE_PU = True
USE_RAST = True
USE_ESA_ASYM = True

RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21
RAST_POST_RESET_ENABLE = False
RAST_POST_RESET_SCALE = 0.0
RAST_POST_RESET_CONFLICT_ONLY = False
RAST_POST_RESET_USE_STATIC_LOSS = False

ESA_ASYM_START_EPOCH = 7
ESA_ASYM_RAMP_END_EPOCH = 15
ESA_ASYM_STOP_EPOCH = 21

# Keep failed/orthogonal branches off.
USE_TCE = False
TCE_LAMBDA_MAX = 0.0

USE_HBNS_LITE = False
HBNS_LAMBDA_MAX = 0.0

USE_EPR_POS = False
EPR_LAMBDA_MAX = 0.0

USE_DARE = False
USE_PROTO_CONTRAST = False
LAMBDA_PROTO_MAX = 0.0

# LCEG-v1: Late Core-Extent Guard, active only in epoch26-35.
USE_LCEG = True
LCEG_VERSION = "v1_late_core_extent_guard"

LCEG_START_EPOCH = 26
LCEG_RAMP_END_EPOCH = 28
LCEG_STOP_EPOCH = 36

LCEG_COVER_CACHE_ROOT = "../datasets/cache/lceg_cover_cache/dinov1-s8/long35_epoch025"
LCEG_COVER_MODEL = "student"
LCEG_COVER_EPOCH = 25

LCEG_USE_CORE_GUARD = True
LCEG_USE_LOST_EXTENT = True
LCEG_USE_NEW_BOUNDARY = True
LCEG_USE_UNKNOWN = False
LCEG_EXCLUDE_BG_CORE = True

LCEG_USE_DINO_MARGIN = True
LCEG_FEATURE_SIZE = 37
LCEG_DETACH_PROTO = True
LCEG_LOST_MARGIN_THRESH = -0.02
LCEG_NEW_MARGIN_THRESH = 0.05

LCEG_LOST_COVER_PROB_THRESH = 0.40
LCEG_NEW_COVER_PROB_MAX = 0.40

LCEG_CURRENT_BG_CONF_MAX_CORE = 0.98
LCEG_CURRENT_BG_CONF_MAX_EXTENT = 0.95

LCEG_CORE_STUDENT_PROB_MIN = 0.00
LCEG_LOST_STUDENT_PROB_MIN = 0.05
LCEG_NEW_STUDENT_PROB_MIN = 0.15

LCEG_USE_NEAR_FG = True
LCEG_NEAR_FG_RADIUS = 3
LCEG_NEAR_CURRENT_FG_THRESH = 0.50
LCEG_NEAR_COVER_PROB_THRESH = 0.40

LCEG_USE_EDGE_SUPPORT = True
LCEG_EDGE_Q = 0.60

LCEG_USE_IMAGE_GATE_FOR_EXTENT = True
LCEG_SHRINK_AREA_RATIO = 0.98
LCEG_SHRINK_EXTENT_RATIO = 0.95

LCEG_USE_BG_RISK_GATE = True
LCEG_BG_CORE_TEACHER_FG_MAX = 0.020

LCEG_CORE_MAX_RATIO_PER_IMAGE = 0.010
LCEG_LOST_MAX_RATIO_PER_IMAGE = 0.010
LCEG_NEW_MAX_RATIO_PER_IMAGE = 0.003
LCEG_TOTAL_MAX_RATIO_PER_IMAGE = 0.020
LCEG_MIN_PIXELS_PER_IMAGE = 4

LCEG_CORE_TARGET_FLOOR = 0.55
LCEG_LOST_TARGET_FLOOR = 0.45
LCEG_NEW_TARGET_FLOOR = 0.35

LCEG_LAMBDA_MAX = 0.020
LCEG_BRANCH_WEIGHT_CORE = 1.00
LCEG_BRANCH_WEIGHT_LOST = 0.80
LCEG_BRANCH_WEIGHT_NEW = 0.50

LCEG_USE_TEACHER_BG_REWEIGHT = True
LCEG_CORE_BG_TEACHER_MULT = 0.50
LCEG_LOST_BG_TEACHER_MULT = 0.60
LCEG_NEW_BG_TEACHER_MULT = 0.75

LCEG_APPLY_TO_FINAL = True
LCEG_APPLY_TO_COARSE_AUX = True
LCEG_APPLY_TO_BASE_AUX = False
LCEG_COARSE_LOSS_WEIGHT = 0.50

LCEG_DETACH_MASK = True
LCEG_DETACH_COVER = True
LCEG_DETACH_MARGIN = True
LCEG_WEIGHTED_NORMALIZE = True

USE_LCEG_DIAGNOSTIC = True
LCEG_DIAG_LOG_INTERVAL_EPOCH = 1
