from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_long35_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_postreset35_lrfloor_2e5"

MAX_EPOCH = 35
max_epoch = 35
SAVE_EVERY_EPOCH = True
SAVE_INTERVAL = 1

# Keep the original DAGP-Safe + NDR-v1 model unchanged.
HEAD_TYPE = "dagp_safe"
head_type = "dagp_safe"
USE_DAGP_SAFE_HEAD = True
USE_DAGP_HEAD = False
USE_NDR_BRANCH = True
USE_NDR_V2 = False
USE_CSD_V1R = False
USE_CSD_DECODER = False
USE_PA_DAGP = False

# Keep the Long35 optimizer, reset, and teacher-only schedule unchanged.
DINO = dict(DINO)
DINO["lr"] = 0.0006
LR = 0.0006
LR_POLICY = "step_floor"
USE_LR_FLOOR = True
LR_FLOOR = 2e-5
LR_FLOOR_APPLY_AFTER_SCHEDULER_STEP = True
LR_FLOOR_APPLY_AFTER_FINETUNE_RESET = True

FINETUNE_RESET_EPOCH = 20
FINETUNE_RESET_TIMING = "after_epoch"
FINETUNE_RESET_REBUILD_OPTIMIZER = True
FINETUNE_RESET_REBUILD_SCHEDULER = True
FINETUNE_RESET_GLOBAL_STEP = True
FINETUNE_RESET_TEACHER = True
FINETUNE_RESET_FORCE_LR_FLOOR = True
FINETUNE_RESET_LR = 2e-5

TEACHER_FUSION_MODE = "dabe_pu_despl_sched"
DABE_PU_DESPL_STAGE_START = 1
DABE_PU_DESPL_STAGE_END = 20
DABE_PU_DESPL_STATIC_START = 1.0
DABE_PU_DESPL_STATIC_END = 0.05
DABE_PU_DESPL_TEACHER_START = 0.0
DABE_PU_DESPL_TEACHER_END = 0.95
DABE_PU_DESPL_TEACHER_ONLY_START = 21
USE_TEACHER_BINARY_FULL_LOSS = True
USE_TEACHER_SOFT_FULL_LOSS = False
TEACHER_TARGET_MODE = "binary"
DABE_PU_STATIC_TARGET_MODE = "soft"

# Original pre-reset RAST-v1.2 + ESA-Asym path.
USE_RAST = True
RAST_VERSION = "v1.2_esa_asym_postreset35"
RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21
RAST_DISABLE_AFTER_RESET = True
RAST_POST_RESET_ENABLE = False
RAST_POST_RESET_SCALE = 0.0
RAST_POST_RESET_CONFLICT_ONLY = False
RAST_POST_RESET_USE_STATIC_LOSS = False
RAST_APPLY_TO_FINAL = True
RAST_APPLY_TO_COARSE_AUX = True
RAST_APPLY_TO_BASE_AUX = True
RAST_WEIGHTED_LOSS_NORMALIZE = True

USE_ESA_ASYM = True
ESA_ASYM_VERSION = "extent_teacher_bg_routing_v1_postreset35"
ESA_ASYM_START_EPOCH = 7
ESA_ASYM_RAMP_END_EPOCH = 15
ESA_ASYM_STOP_EPOCH = 21
ESA_EXTENT_TEACHER_FG_MULT = 1.0
ESA_MARGIN_FG_LIKE = 0.05
ESA_MARGIN_BG_LIKE = -0.05
ESA_EXTENT_TEACHER_BG_FG_LIKE_MULT = 0.25
ESA_EXTENT_TEACHER_BG_AMBIG_MULT = 0.50
ESA_EXTENT_TEACHER_BG_BG_LIKE_MULT = 1.0
ESA_TOUCH_UNKNOWN = False
ESA_USE_DINO_MARGIN = True
ESA_FEATURE_SIZE = 37
ESA_DETACH_MASK = True
ESA_DETACH_PROTO = True
USE_ESA_DIAGNOSTIC = True
ESA_DIAG_LOG_INTERVAL_EPOCH = 1

# Independent extent-only routing during teacher-only epochs 21-35.
ESA_POST_RESET_ENABLE = True
ESA_POST_RESET_VERSION = "extent_only_keep_v1"
ESA_POST_RESET_START_EPOCH = 21
ESA_POST_RESET_STOP_EPOCH = 36
ESA_POST_RESET_SCALE = 1.0
ESA_POST_RESET_RAMP = False
ESA_POST_RESET_MODE = "extent_only"
ESA_POST_RESET_EXTENT_TEACHER_FG_MULT = 1.0
ESA_POST_RESET_EXTENT_TEACHER_BG_FG_LIKE_MULT = 0.25
ESA_POST_RESET_EXTENT_TEACHER_BG_AMBIG_MULT = 0.50
ESA_POST_RESET_EXTENT_TEACHER_BG_BG_LIKE_MULT = 1.0
ESA_POST_RESET_TOUCH_UNKNOWN = False
ESA_POST_RESET_USE_CORE_CONFLICT = False
ESA_POST_RESET_USE_RAST_UNKNOWN = False
ESA_POST_RESET_APPLY_TO_FINAL = True
ESA_POST_RESET_APPLY_TO_COARSE_AUX = True
ESA_POST_RESET_APPLY_TO_BASE_AUX = True

# Keep unrelated experimental branches disabled.
USE_LCEG = False
USE_TCE = False
USE_CSSD = False
USE_HR_BFR = False
USE_HBNS_LITE = False
HBNS_LAMBDA_MAX = 0.0
USE_EPR_POS = False
EPR_LAMBDA_MAX = 0.0
USE_PROTO_CONTRAST = False
LAMBDA_PROTO_MAX = 0.0
USE_MULTI_VIEW_FEATURE = False
use_multi_view_feature = False
USE_VIEW_CONSISTENCY = False
use_view_consistency = False
USE_TADR_ROUTER = False
USE_DABE_AWARE_LOSS = False
USE_DABE_TVERSKY_LOSS = False
USE_DABE_AREA_GUARD = False
GKD_MODE = "off"
USE_GKD_LITE = False
