"""Clean-DP with the isolated Clean-native ECST-v1 Teacher router."""

from configs.dinov1_s8_dabe_clean_v1_dp_ecst_dagp_uncgate_ndr_long45_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = (
    "dinov1_s8_dabe_clean_v1_dp_clean_ecst_v1_r1_"
    "dagp_uncgate_ndr_long45_lrfloor_2e5"
)

TEACHER_ROUTING_MODE = "clean_ecst"
USE_ECST = False
USE_ECST_MINIMAL = False
USE_ECST_CLEAN = True

# The Clean-native router must not even materialize the old PU region cache.
USE_DABE_PU = False
DABE_PU_ROOT = ""
DABE_CLEAN_USE_LEGACY_ECST_REGIONS = False
DABE_CLEAN_LEGACY_ROUTING_ONLY = False
DABE_CLEAN_LEGACY_REGION_ROOT = ""

ECST_CLEAN_VERSION = "v1_signed_conf_ring_asym"

ECST_CLEAN_START_EPOCH = 7
ECST_CLEAN_RAMP_END_EPOCH = 15
ECST_CLEAN_STOP_EPOCH = 21

ECST_CLEAN_MEMORY_UPDATE_START_EPOCH = 1
ECST_CLEAN_MEMORY_UPDATE_END_EPOCH = 20
ECST_CLEAN_TEMPORAL_RHO = 0.9
ECST_CLEAN_MIN_HISTORY = 3
ECST_CLEAN_VARIANCE_TAU = 0.02
ECST_CLEAN_USE_PREUPDATE_STATS = True
ECST_CLEAN_MEMORY_DTYPE = "float16"
ECST_CLEAN_RESET_MEMORY_AT_FINETUNE_RESET = True

ECST_CLEAN_RING_RADIUS = 1
ECST_CLEAN_CONFLICT_FLOOR = 0.20
ECST_CLEAN_NEGATIVE_WEIGHT_FLOOR = 0.25
ECST_CLEAN_MARGIN_TAU = 0.05
ECST_CLEAN_WEIGHT_MIN = 0.20
ECST_CLEAN_WEIGHT_MAX = 1.00

ECST_CLEAN_APPLY_TO_FINAL = True
ECST_CLEAN_APPLY_TO_COARSE_AUX = True
ECST_CLEAN_APPLY_TO_BASE_AUX = True

MAX_EPOCH = 45
STOP_AFTER_EPOCH = 0
SAVE_EVERY_EPOCH = True
SAVE_INTERVAL = 1
