from configs.dinov1_s8_despl_only_teacher_cache import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_only_mlcfd"

HEAD_TYPE = "ml_context"

USE_MULTI_LEVEL_FEATURE = True
MULTI_LEVEL_FEATURE_ROOT = "../datasets/cache/features_cache_ml_fp16"
MULTI_LEVEL_LAYERS = [4, 8, 12]
MULTI_LEVEL_FEATURE_TYPE = "key"
MULTI_LEVEL_FEATURE_DTYPE = "float16"
ML_FEATURE_PREFLIGHT_MODE = "sample"
ML_FEATURE_PREFLIGHT_SAMPLES = 32

MLC_HIDDEN = 128
MLC_USE_SEMANTIC_GATE = True
MLC_USE_SCE_LITE = True
MLC_USE_PCF = True
MLC_PCF_DILATIONS = [1, 2, 3, 5]
MLC_RES_SCALE_INIT = 0.1

USE_BASE_AUX_LOSS = True
LAMBDA_BASE_AUX = 0.3
LAMBDA_BASE_AUX_AFTER_RESET = 0.1

NUM_WORKERS = 2
DATALOADER_PERSISTENT_WORKERS = True
DATALOADER_PREFETCH_FACTOR = 2

USE_DESPL_PSEUDO = True
USE_DESPL_LIGHT_CACHE = True

P_INIT_MODE = "despl_only"
P_INIT_DESPL_WEIGHT = 1.0
P_INIT_FIXED_WEIGHT = 0.0

PSEUDO_USE_GCM = False
PSEUDO_USE_TEACHER = False
PSEUDO_USE_LOCAL_ATTN = False

USE_PSTA = False
USE_MNP = False
DINO_USE_LORA = False
USE_CNN_DETAIL_BRANCH = False
USE_AFF = False
USE_DUAL_FG_BG_HEAD = False
USE_BOUNDARY_HEAD = False

LAMBDA_MNP = 0.0
LAMBDA_LOCAL = 0.0
LAMBDA_PSTA = 0.0
LAMBDA_CONTRAST = 0.0
LAMBDA_BOUNDARY = 0.0
LAMBDA_ENTROPY = 0.0
LAMBDA_ANCHOR = 0.0
