from configs.dinov1_s8_despl_only_teacher_cache import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_only_gkd_branch_v2safe"

GKD_MODE = "branch"
USE_GKD_LITE = True

# Keep DESPL-only path unchanged.
HEAD_TYPE = "simple"
USE_GATED_CONTEXT_HEAD = False

USE_DESPL_PSEUDO = True
USE_DESPL_LIGHT_CACHE = True
P_INIT_MODE = "despl_only"
P_INIT_DESPL_WEIGHT = 1.0
P_INIT_FIXED_WEIGHT = 0.0

USE_QRA = False
USE_CCR = False
USE_DREPP = False
USE_DRE_SAFE_PRIOR = False
USE_DESPL_PAPER_CACHE = False

PSEUDO_USE_GCM = False
USE_GCM = False
PSEUDO_USE_TEACHER = False
PSEUDO_USE_LOCAL_ATTN = False

USE_PSTA = False
USE_MNP = False
DINO_USE_LORA = False
USE_CNN_DETAIL_BRANCH = False
USE_AFF = False
USE_DUAL_FG_BG_HEAD = False
USE_BOUNDARY_HEAD = False

LAMBDA_MNP = 0.0
LAMBDA_LOCAL = 0.0
LAMBDA_PSTA = 0.0
LAMBDA_CONTRAST = 0.0
LAMBDA_BOUNDARY = 0.0
LAMBDA_ENTROPY = 0.0
LAMBDA_ANCHOR = 0.0

USE_DESPL_ANCHOR_PBCE = False
USE_LATE_DESPL_ANCHOR_LOSS = False
USE_PURE_DESPL_SUPERVISION = False
USE_FAST_TEACHER_FUSION = False
TEACHER_FUSION_MODE = "default"

# ------------------------------------------------------------
# GKD-Branch v2-safe
# ------------------------------------------------------------
GKD_ENABLE_STRICT_HIGH_GATE = True
GKD_ENABLE_HARD_DOWNGRADE = True
GKD_ENABLE_DYNAMIC_LOW = True

GKD_V2_Q_HIGH = 0.90
GKD_V2_Q_NORMAL = 0.60

GKD_HIGH_AREA_MIN = 0.01
GKD_HIGH_AREA_MAX = 0.60
GKD_HIGH_CC_MAX = 4
GKD_HIGH_LCC_MIN = 0.70
GKD_HIGH_EDGE_MAX = 0.15
GKD_HIGH_AGREE_MIN = 0.50

GKD_DOWNGRADE_CC_MAX = 6
GKD_DOWNGRADE_AGREE_MIN = 0.45
GKD_DOWNGRADE_AREA_MAX = 0.70
GKD_DOWNGRADE_EDGE_MAX = 0.20

GKD_STATIC_LOW_AREA_MIN = 0.003
GKD_STATIC_LOW_AREA_MAX = 0.85
GKD_STATIC_LOW_CC_MAX = 15
GKD_STATIC_LOW_LCC_MIN = 0.20
GKD_STATIC_LOW_EDGE_MAX = 0.45
GKD_STATIC_LOW_AGREE_MIN = 0.15

GKD_DYNAMIC_LOW_START_EPOCH = 6
GKD_TEACHER_DESPL_LOW_IOU = 0.35
GKD_TEACHER_DESPL_NORMAL_IOU = 0.55
GKD_TEACHER_AREA_MIN = 0.005
GKD_TEACHER_AREA_MAX = 0.80

GKD_BRANCH_L1_WEIGHT = 0.3
GKD_BRANCH_MSE_WEIGHT = 0.3
GKD_BRANCH_LATE_STRENGTH = 0.0

GKD_BRANCH_LOW_MODE = "teacher_l1_plus_teacher_bce"
GKD_LOW_TEACHER_BCE_WEIGHT = 0.3

GKD_USE_ENTROPY_PIXEL_WEIGHT = False
GKD_ENTROPY_WEIGHT_MIN = 0.80

GKD_LOG_GRADE_TRANSITIONS = True
GKD_LOG_DYNAMIC_LOW_REASONS = True
