from configs.dinov1_s8_despl_only_teacher_cache import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_only_gated_head"

HEAD_TYPE = "gated_context"
USE_GATED_CONTEXT_HEAD = True
GATED_HEAD_HIDDEN = 64
GATED_HEAD_GAMMA_INIT = 0.0

USE_DESPL_PSEUDO = True
P_INIT_MODE = "despl_only"
PSEUDO_USE_FIXED = False
PSEUDO_USE_DESPL = True
PSEUDO_USE_GCM = False
PSEUDO_USE_TEACHER = False
PSEUDO_USE_LOCAL_ATTN = False
P_INIT_DESPL_WEIGHT = 1.0
P_INIT_FIXED_WEIGHT = 0.0

DINO_USE_LORA = False
USE_CNN_DETAIL_BRANCH = False
USE_AFF = False
USE_DUAL_FG_BG_HEAD = False
USE_BOUNDARY_HEAD = False
USE_PSTA = False
USE_MNP = False

LAMBDA_MNP = 0.0
LAMBDA_LOCAL = 0.0
LAMBDA_PSTA = 0.0
LAMBDA_CONTRAST = 0.0
LAMBDA_BOUNDARY = 0.0
LAMBDA_ENTROPY = 0.0
LAMBDA_ANCHOR = 0.0
