from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_puconf_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_pubal_v2_lrfloor_2e5"

USE_DABE_PU = True
DABE_PU_VERSION = "pu_v11"
DABE_PU_ROOT = "../datasets/cache/dabe_pu_v11_pseudo_cache/dinov1-s8"
P_INIT_MODE = "dabe_pu_v11"

TEACHER_FUSION_MODE = "dabe_pu_balanced_v2"
USE_DABE_PU_STATIC_LOSS = True
USE_TEACHER_CONF_LOSS = True
USE_DABE_PU_GROUP_BALANCED_STATIC = True
USE_TEACHER_CONF_BALANCED = True

DABE_PU_V2_STAGE1_END = 3
DABE_PU_V2_STAGE2_START = 4
DABE_PU_V2_STAGE2_END = 15
DABE_PU_V2_STATIC_STAGE2_START = 0.85
DABE_PU_V2_STATIC_STAGE2_END = 0.45
DABE_PU_V2_TEACHER_STAGE2_START = 0.15
DABE_PU_V2_TEACHER_STAGE2_END = 0.55
DABE_PU_V2_STAGE3_START = 16
DABE_PU_V2_STATIC_STAGE3 = 0.30
DABE_PU_V2_TEACHER_STAGE3 = 0.70

PU_STATIC_LAMBDA_FG = 1.00
PU_STATIC_LAMBDA_FG_FALLBACK = 0.35
PU_STATIC_LAMBDA_BG = 0.50
PU_STATIC_LAMBDA_EXTENT = 0.10
PU_STATIC_LAMBDA_UNKNOWN = 0.00
PU_STATIC_GROUP_EPS = 1e-6

TEACHER_CONF_FG_THRESH = 0.70
TEACHER_CONF_BG_THRESH = 0.20
TEACHER_CONF_IGNORE_PU_CORE = True
TEACHER_CONF_LAMBDA_FG = 1.00
TEACHER_CONF_LAMBDA_BG = 0.30
TEACHER_CONF_GROUP_EPS = 1e-6
TEACHER_CONF_BG_MAX_RATIO = 0.15
TEACHER_CONF_BG_TO_FG_MAX = 5.0
TEACHER_CONF_BG_MIN_PIXELS = 128
TEACHER_CONF_BG_CAP_IF_NO_FG_RATIO = 0.05

FINETUNE_RESET_EPOCH = -1
FINETUNE_RESET_REBUILD_OPTIMIZER = False
FINETUNE_RESET_REBUILD_SCHEDULER = False
FINETUNE_RESET_GLOBAL_STEP = False
FINETUNE_RESET_TEACHER = False

USE_DABE_PSEUDO = False
USE_DABE_AWARE_LOSS = False
USE_DABE_TVERSKY_LOSS = False
USE_DABE_AREA_GUARD = False
USE_PROTO_CONTRAST = False
LAMBDA_PROTO_MAX = 0.0
USE_MULTI_VIEW_FEATURE = False
MULTI_VIEW_TYPES = []
USE_VIEW_CONSISTENCY = False
LAMBDA_VIEW_MAX = 0.0
GKD_MODE = "off"
USE_GKD_LITE = False
USE_TADR_ROUTER = False
