from configs.dinov1_s8_despl_dagp_uncgate_ndr_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_dagp_uncgate_ndr_tadr_lrfloor_2e5"

NDR_BETA_MAX = 0.10
NDR_RESIDUAL_CLIP = 2.0
NDR_GATE_MODE = "uncertainty_edge_boost"

NDR_INPUT_RGB = True
NDR_INPUT_SOBEL = True
NDR_INPUT_COARSE_PROB = True
NDR_IN_CHANNELS = 5

USE_NDR_COARSE_AUX = True
LAMBDA_NDR_COARSE_AUX = 0.5

NDR_USE_RES_REG = False
NDR_RES_REG_WEIGHT = 0.001

USE_TADR_ROUTER = True
TADR_ROUTER_IN_CHANNELS = 4
TADR_ROUTER_HIDDEN = 16
TADR_ROUTER_NUM_LAYERS = 2
TADR_ROUTER_ACT = "gelu"

TADR_USE_COARSE_PROB = True
TADR_USE_UNCERTAINTY = True
TADR_USE_SOBEL = True
TADR_USE_COARSE_BOUNDARY = True

TADR_ROUTER_INIT_BIAS = 2.0
TADR_ROUTER_ZERO_INIT_OUT = True
TADR_ROUTER_DETACH_INPUTS = True
TADR_ROUTER_MIN = 0.0
TADR_ROUTER_MAX = 1.0

TADR_DEBUG_FIRST_BATCH = True
