from configs.dinov1_s8_despl_only_dagp_safe_uncgate_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_dagp_uncgate_ndr_lrfloor_2e5"

MAX_EPOCH = 25
FINETUNE_RESET_EPOCH = 21

LR_POLICY = "step_floor"
USE_LR_FLOOR = True
LR_FLOOR = 2e-5

HEAD_TYPE = "dagp_safe"
USE_DAGP_SAFE_HEAD = True

DAGP_SAFE_HIDDEN = 64
DAGP_SAFE_TOPK = 12
DAGP_SAFE_TAU = 0.07
DAGP_SAFE_ALPHA_MAX = 0.05
DAGP_SAFE_GAMMA_MAX = 0.03
DAGP_SAFE_WARMUP_EPOCH = 6
DAGP_SAFE_RAMP_START_EPOCH = 7
DAGP_SAFE_RAMP_END_EPOCH = 15
DAGP_SAFE_USE_PROB_GATE = True
DAGP_SAFE_PROB_GATE_SIGMA = 0.25
DAGP_SAFE_USE_UNCERTAINTY_OUTPUT_GATE = True
DAGP_SAFE_UNCERTAINTY_POWER = 1.0
DAGP_SAFE_UNCERTAINTY_MIN = 0.0
DAGP_SAFE_UNCERTAINTY_MAX = 1.0
DAGP_SAFE_UNCERTAINTY_DETACH = True

USE_BASE_AUX_LOSS = True
LAMBDA_BASE_AUX = 0.5
LAMBDA_BASE_AUX_AFTER_RESET = 0.3
BASE_AUX_NORMALIZE = True

USE_NDR_BRANCH = True
NDR_INPUT_RGB = True
NDR_INPUT_SOBEL = True
NDR_INPUT_COARSE_PROB = True
NDR_IN_CHANNELS = 5
NDR_HIDDEN = 32
NDR_NUM_LAYERS = 3
NDR_USE_GN = True
NDR_GN_GROUPS = 4
NDR_ACT = "gelu"
NDR_ZERO_INIT_OUT = True
NDR_RESIDUAL_CLIP = 2.0

NDR_BETA_MAX = 0.10
NDR_WARMUP_EPOCH = 6
NDR_RAMP_START_EPOCH = 7
NDR_RAMP_END_EPOCH = 15

NDR_USE_UNCERTAINTY_GATE = True
NDR_USE_EDGE_GATE = True
NDR_GATE_MODE = "uncertainty_edge_boost"

USE_NDR_COARSE_AUX = True
LAMBDA_NDR_COARSE_AUX = 0.5
NDR_USE_RES_REG = False
NDR_RES_REG_WEIGHT = 0.001

NDR_DEBUG_FIRST_BATCH = True
