from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_long35_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_long35_tce_v1_lrfloor_2e5"

# Keep Long35 behavior fixed for epoch1-30.
MAX_EPOCH = 35
max_epoch = 35
SAVE_EVERY_EPOCH = True
SAVE_EPOCH_CKPT = True
CKPT_SAVE_EVERY_EPOCH = True
SAVE_ALL_EPOCHS = True
SAVE_INTERVAL = 1

DINO = dict(DINO)
DINO["lr"] = 0.0006
LR = 0.0006
LR_POLICY = "step_floor"
USE_LR_FLOOR = True
LR_FLOOR = 2e-5
LR_LINEAR_STAGE1_EPOCHS = 19
LR_LINEAR_STAGE2_EPOCHS = 0
LR_FLOOR_MODE = "global"
LR_FLOOR_APPLY_AFTER_SCHEDULER_STEP = True
LR_FLOOR_APPLY_AFTER_FINETUNE_RESET = True

FINETUNE_RESET_EPOCH = 20
FINETUNE_RESET_TIMING = "after_epoch"
FINETUNE_RESET_REBUILD_OPTIMIZER = True
FINETUNE_RESET_REBUILD_SCHEDULER = True
FINETUNE_RESET_GLOBAL_STEP = True
FINETUNE_RESET_TEACHER = True
FINETUNE_RESET_FORCE_LR_FLOOR = True
FINETUNE_RESET_LR = 2e-5

TEACHER_FUSION_MODE = "dabe_pu_despl_sched"
DABE_PU_DESPL_STAGE_START = 1
DABE_PU_DESPL_STAGE_END = 20
DABE_PU_DESPL_STATIC_START = 1.0
DABE_PU_DESPL_STATIC_END = 0.05
DABE_PU_DESPL_TEACHER_START = 0.0
DABE_PU_DESPL_TEACHER_END = 0.95
DABE_PU_DESPL_TEACHER_ONLY_START = 21

USE_DABE_PU = True
USE_RAST = True
USE_ESA_ASYM = True
RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21
ESA_ASYM_START_EPOCH = 7
ESA_ASYM_RAMP_END_EPOCH = 15
ESA_ASYM_STOP_EPOCH = 21
RAST_POST_RESET_ENABLE = False
RAST_POST_RESET_SCALE = 0.0
RAST_POST_RESET_CONFLICT_ONLY = False
RAST_POST_RESET_USE_STATIC_LOSS = False

USE_HBNS_LITE = False
HBNS_LAMBDA_MAX = 0.0
USE_EPR_POS = False
EPR_LAMBDA_MAX = 0.0
USE_DARE = False
USE_PROTO_CONTRAST = False
LAMBDA_PROTO_MAX = 0.0

# TCE-v1: Temporal Coverage Expansion, active only in epoch31-35.
USE_TCE = True
TCE_VERSION = "v1_temporal_coverage_expansion"
TCE_START_EPOCH = 31
TCE_RAMP_END_EPOCH = 32
TCE_STOP_EPOCH = 36
TCE_COVER_CACHE_ROOT = "../datasets/cache/tce_cover_cache/dinov1-s8/long35_epoch030"
TCE_COVER_MODEL = "student"
TCE_COVER_EPOCH = 30

TCE_USE_LOST_COVER = True
TCE_USE_NEW_BOUNDARY = True
TCE_REGION = "extent"
TCE_USE_UNKNOWN = False
TCE_EXCLUDE_BG_CORE = True
TCE_USE_DINO_MARGIN = True
TCE_FEATURE_SIZE = 37
TCE_DETACH_PROTO = True
TCE_LOST_MARGIN_THRESH = 0.05
TCE_NEW_MARGIN_THRESH = 0.10
TCE_COVER_CONF_THRESH = 0.60
TCE_CURRENT_BG_CONF_MAX = 0.90

TCE_USE_NEAR_CURRENT_FG = True
TCE_NEAR_FG_THRESH = 0.50
TCE_NEAR_FG_RADIUS = 3
TCE_NEW_STUDENT_PROB_THRESH = 0.25
TCE_USE_EDGE_SUPPORT = True
TCE_EDGE_Q = 0.60

TCE_USE_IMAGE_GATE = True
TCE_SHRINK_AREA_RATIO = 0.90
TCE_SHRINK_EXTENT_RATIO = 0.85
TCE_USE_BG_RISK_GATE = True
TCE_BG_CORE_TEACHER_FG_MAX = 0.015

TCE_LOST_MAX_RATIO_PER_IMAGE = 0.004
TCE_NEW_MAX_RATIO_PER_IMAGE = 0.002
TCE_TOTAL_MAX_RATIO_PER_IMAGE = 0.005
TCE_MIN_PIXELS_PER_IMAGE = 4

TCE_USE_LOWER_BOUND_LOSS = True
TCE_LAMBDA_MAX = 0.010
TCE_LOST_TARGET_FLOOR = 0.45
TCE_NEW_TARGET_FLOOR = 0.35

TCE_USE_TEACHER_BG_REWEIGHT = True
TCE_LOST_BG_TEACHER_MULT = 0.60
TCE_NEW_BG_TEACHER_MULT = 0.75
TCE_APPLY_TO_FINAL = True
TCE_APPLY_TO_COARSE_AUX = False
TCE_APPLY_TO_BASE_AUX = False
TCE_DETACH_MASK = True
TCE_DETACH_COVER = True
TCE_DETACH_MARGIN = True
TCE_WEIGHTED_NORMALIZE = True

USE_TCE_DIAGNOSTIC = True
TCE_DIAG_LOG_INTERVAL_EPOCH = 1
