from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_tepr_lite_long35_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = (
    "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_"
    "tepr_lite_v11_asymneg_long35_lrfloor_2e5"
)

# TEPR-v1.1 remains a replacement for RAST/ESA teacher routing.
USE_RAST = False
USE_ESA_ASYM = False
ESA_POST_RESET_ENABLE = False
USE_ESA_BER = False

USE_TEPR_LITE = True
TEPR_VERSION = "lite_v1_1_state_conditional_asymneg"
TEPR_ROUTING_MODE = "state_conditional_asymneg"

TEPR_START_EPOCH = 7
TEPR_RAMP_END_EPOCH = 15
TEPR_STOP_EPOCH = 21

TEPR_MEMORY_UPDATE_START_EPOCH = 1
TEPR_MEMORY_UPDATE_END_EPOCH = 20
TEPR_TEMPORAL_RHO = 0.90
TEPR_MIN_HISTORY = 3
TEPR_MEMORY_DTYPE = "float16"
TEPR_USE_PREUPDATE_STATS = True
TEPR_RESET_MEMORY_AT_FINETUNE_RESET = True

TEPR_TEMPORAL_SCOPE = "extent_teacher_bg_only"
TEPR_VARIANCE_TAU = 0.02
TEPR_CONF_GAMMA = 1.0
TEPR_INSUFFICIENT_HISTORY_MODE = "dino_only"

TEPR_CORE_MODE = "current_binary_exact"
TEPR_CORE_CONFLICT_WEIGHT = 0.20
TEPR_USE_TEMPORAL_ON_CORE = False

TEPR_EXTENT_FG_WEIGHT = 1.00
TEPR_EXTENT_BG_WEIGHT_FLOOR = 0.25
TEPR_EXTENT_DINO_LAMBDA = 1.386294
TEPR_MARGIN_TAU = 0.05
TEPR_USE_TEMPORAL_ON_EXTENT_FG = False
TEPR_USE_TEMPORAL_ON_EXTENT_BG = True

TEPR_UNKNOWN_MODE = "fixed"
TEPR_UNKNOWN_WEIGHT = 0.50
TEPR_USE_TEMPORAL_ON_UNKNOWN = False

TEPR_OTHER_WEIGHT = 1.00
TEPR_WEIGHT_MIN = 0.20
TEPR_WEIGHT_MAX = 1.00

TEPR_APPLY_TO_FINAL = True
TEPR_APPLY_TO_COARSE_AUX = True
TEPR_APPLY_TO_BASE_AUX = True

TEPR_LOG_INTERVAL_EPOCH = 1
TEPR_DEBUG_FIRST_BATCH = True

USE_HBNS_LITE = False
HBNS_LAMBDA_MAX = 0.0
USE_EPR_POS = False
EPR_LAMBDA_MAX = 0.0

MAX_EPOCH = 35
max_epoch = 35
SAVE_EVERY_EPOCH = True
SAVE_INTERVAL = 1
