from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_desplsched_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v1_lrfloor_2e5"

USE_RAST = True
RAST_VERSION = "v1"

RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21

RAST_CONFLICT_TEACHER_MULT = 0.20
RAST_EXTENT_TEACHER_MULT = 0.75
RAST_UNKNOWN_TEACHER_MULT = 0.25
RAST_OTHER_TEACHER_MULT = 1.00

RAST_STATIC_FG_CORE_MULT = 1.00
RAST_STATIC_BG_CORE_MULT = 1.00
RAST_STATIC_EXTENT_MULT = 1.00
RAST_STATIC_UNKNOWN_MULT = 1.00

RAST_APPLY_TO_FINAL = True
RAST_APPLY_TO_COARSE_AUX = True
RAST_APPLY_TO_BASE_AUX = True

RAST_DISABLE_AFTER_RESET = True
RAST_WEIGHTED_LOSS_NORMALIZE = True

RAST_LOG_INTERVAL_EPOCH = 1

P_INIT_MODE = "dabe_pu_v11_desplsched"
TEACHER_FUSION_MODE = "dabe_pu_despl_sched"
USE_DABE_PU = True
DABE_PU_VERSION = "pu_v11"
DABE_PU_ROOT = "../datasets/cache/dabe_pu_v11_pseudo_cache/dinov1-s8"

DABE_PU_STATIC_TARGET_MODE = "soft"
USE_DABE_PU_HARD_STATIC_TARGET = False
DABE_PU_HARD_KEEP_WEIGHT_MAP = True

USE_TEACHER_BINARY_FULL_LOSS = True
USE_TEACHER_SOFT_FULL_LOSS = False
TEACHER_TARGET_MODE = "binary"
USE_TEACHER_CONF_LOSS = False
USE_TEACHER_CONF_BALANCED = False

USE_DABE_PU_GROUP_BALANCED_STATIC = False
USE_DABE_OEM = False
USE_DABE_OEM_DYNAMIC_EXTENT = False
USE_DABE_PU_SEED_STATIC_LOSS = False

USE_DABE_AWARE_LOSS = False
USE_DABE_TVERSKY_LOSS = False
USE_DABE_AREA_GUARD = False

USE_PROTO_CONTRAST = False
LAMBDA_PROTO_MAX = 0.0

use_multi_view_feature = False
USE_MULTI_VIEW_FEATURE = False
multi_view_types = []
MULTI_VIEW_TYPES = []
use_view_consistency = False
USE_VIEW_CONSISTENCY = False
lambda_view_max = 0.0
LAMBDA_VIEW_MAX = 0.0

GKD_MODE = "off"
USE_GKD_LITE = False
USE_TADR_ROUTER = False
