from configs.dinov1_s8_dabev2_dagp_uncgate_ndr_sticky_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabev2_dagp_uncgate_ndr_aware_sticky_lrfloor_2e5"

TEACHER_FUSION_MODE = "dabe_sticky"

DABE_STICKY_E1_E6_DABE_WEIGHT = 1.00

DABE_STICKY_STAGE2_START = 7
DABE_STICKY_STAGE2_END = 15
DABE_STICKY_STAGE2_DABE_START = 0.85
DABE_STICKY_STAGE2_DABE_END = 0.55

DABE_STICKY_STAGE3_START = 16
DABE_STICKY_STAGE3_END = 20
DABE_STICKY_STAGE3_DABE_START = 0.55
DABE_STICKY_STAGE3_DABE_END = 0.25

DABE_STICKY_AFTER_EPOCH = 21
DABE_STICKY_AFTER_DABE_WEIGHT = 0.25
DABE_STICKY_AFTER_TEACHER_WEIGHT = 0.75

FINETUNE_RESET_EPOCH = -1
FINETUNE_RESET_REBUILD_OPTIMIZER = False
FINETUNE_RESET_REBUILD_SCHEDULER = False
FINETUNE_RESET_GLOBAL_STEP = False

USE_DABE_AWARE_LOSS = True
DABE_AWARE_USE_TRIMAP = True
DABE_AWARE_CORE_LOCK = True
DABE_AWARE_WEIGHTED_BCE = True

DABE_FG_CORE_WEIGHT = 2.0
DABE_BG_CORE_WEIGHT = 1.2
DABE_UNCERTAIN_WEIGHT = 0.20
DABE_EVIDENCE_WEIGHT_SCALE = 0.40
DABE_CORE_THRESH = 0.5

USE_DABE_TVERSKY_LOSS = True
DABE_TVERSKY_WEIGHT = 0.30
DABE_TVERSKY_ALPHA_FP = 0.30
DABE_TVERSKY_BETA_FN = 0.70
DABE_TVERSKY_EPS = 1e-6

USE_DABE_AREA_GUARD = True
DABE_AREA_GUARD_START_EPOCH = 7
DABE_AREA_GUARD_WEIGHT = 0.02
DABE_AREA_GUARD_RATIO = 0.85
DABE_AREA_GUARD_USE_SOFT_AREA = True
