from configs.dinov1_s8_dabev2_dagp_uncgate_ndr_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabev2_dagp_uncgate_ndr_sticky_lrfloor_2e5"

TEACHER_FUSION_MODE = "dabe_sticky"

DABE_STICKY_E1_E6_DABE_WEIGHT = 1.00

DABE_STICKY_STAGE2_START = 7
DABE_STICKY_STAGE2_END = 15
DABE_STICKY_STAGE2_DABE_START = 0.85
DABE_STICKY_STAGE2_DABE_END = 0.55

DABE_STICKY_STAGE3_START = 16
DABE_STICKY_STAGE3_END = 20
DABE_STICKY_STAGE3_DABE_START = 0.55
DABE_STICKY_STAGE3_DABE_END = 0.25

DABE_STICKY_AFTER_EPOCH = 21
DABE_STICKY_AFTER_DABE_WEIGHT = 0.15
DABE_STICKY_AFTER_TEACHER_WEIGHT = 0.85

FINETUNE_RESET_EPOCH = -1
FINETUNE_RESET_REBUILD_OPTIMIZER = False
FINETUNE_RESET_REBUILD_SCHEDULER = False
FINETUNE_RESET_GLOBAL_STEP = False
