from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_relaxamb_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_hbns_lite_diag_lrfloor_2e5"

USE_RAST = True
RAST_VERSION = "v1.2_hbns_lite_diag"

RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21

RAST_CONFLICT_TEACHER_MULT = 0.20
RAST_EXTENT_TEACHER_MULT = 1.00
RAST_UNKNOWN_TEACHER_MULT = 0.50
RAST_OTHER_TEACHER_MULT = 1.00

RAST_POST_RESET_ENABLE = False
RAST_POST_RESET_SCALE = 0.00
RAST_POST_RESET_CONFLICT_ONLY = False
RAST_POST_RESET_USE_STATIC_LOSS = False

RAST_APPLY_TO_FINAL = True
RAST_APPLY_TO_COARSE_AUX = True
RAST_APPLY_TO_BASE_AUX = True
RAST_WEIGHTED_LOSS_NORMALIZE = True

USE_HBNS_LITE = True
HBNS_VERSION = "lite_v1"

HBNS_START_EPOCH = 7
HBNS_RAMP_END_EPOCH = 15
HBNS_STOP_EPOCH = 21

HBNS_LAMBDA_MAX = 0.01
HBNS_APPLY_TO_FINAL = True
HBNS_APPLY_TO_COARSE_AUX = True
HBNS_APPLY_TO_BASE_AUX = False

HBNS_STUDENT_PROB_THRESH = 0.50
HBNS_LOW_TARGET_THRESH = 0.15
HBNS_LOW_TARGET_WEIGHT_THRESH = 0.50

HBNS_USE_BG_CORE = True
HBNS_USE_LOW_TARGET_BG = True
HBNS_USE_UNKNOWN_BG_LIKE = True
HBNS_USE_BG_DILATION_RING = False
HBNS_BG_RING_RADIUS = 3

HBNS_MAX_RATIO_PER_IMAGE = 0.05
HBNS_MIN_PIXELS_PER_IMAGE = 8

HBNS_DETACH_MASK = True
HBNS_WEIGHTED_NORMALIZE = True

USE_ESA_DIAGNOSTIC = True
ESA_DIAG_LOG_INTERVAL_EPOCH = 1
