from configs.dinov1_s8_despl_only_teacher_cache import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_only_fast_t10"

USE_FAST_TEACHER_FUSION = True
TEACHER_FUSION_MODE = "fast_t10"
FAST_T10_START_EPOCH = 2
FAST_T10_END_EPOCH = 10
FAST_T10_MAX_TEACHER_WEIGHT = 0.95
FAST_T10_HOLD_END_EPOCH = 20

USE_PURE_DESPL_SUPERVISION = False

USE_DESPL_ANCHOR_PBCE = False
ANCHOR_PBCE_LAMBDA_EARLY = 0.0
ANCHOR_PBCE_LAMBDA_LATE = 0.0

HEAD_TYPE = "simple"

USE_DESPL_PSEUDO = True
USE_DESPL_LIGHT_CACHE = True
P_INIT_MODE = "despl_only"
P_INIT_DESPL_WEIGHT = 1.0
P_INIT_FIXED_WEIGHT = 0.0

PSEUDO_USE_GCM = False
PSEUDO_USE_TEACHER = False
PSEUDO_USE_LOCAL_ATTN = False

USE_PSTA = False
USE_MNP = False
DINO_USE_LORA = False
USE_CNN_DETAIL_BRANCH = False
USE_AFF = False
USE_DUAL_FG_BG_HEAD = False
USE_BOUNDARY_HEAD = False

LAMBDA_MNP = 0.0
LAMBDA_LOCAL = 0.0
LAMBDA_PSTA = 0.0
LAMBDA_CONTRAST = 0.0
LAMBDA_BOUNDARY = 0.0
LAMBDA_ENTROPY = 0.0
LAMBDA_ANCHOR = 0.0
