from configs.dinov1_s8_despl_dagp_uncgate_ndr_mvflip_proto import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_dagp_uncgate_ndr_mvflip_proto_hs"

USE_MULTI_VIEW_FEATURE = True
MULTI_VIEW_TYPES = ["hflip"]
HFLIP_FEATURE_CACHE_ROOT = "../datasets/cache/features_cache_hflip"

USE_VIEW_CONSISTENCY = False
LAMBDA_VIEW_MAX = 0.0

USE_PROTO_CONTRAST = True
PROTO_MODE = "hard_selective"
LAMBDA_PROTO_MAX = 0.01

PROTO_FEATURE_SOURCE = "dagp_semantic"
PROTO_USE_PROJ_HEAD = True
PROTO_PROJ_HIDDEN = 64
PROTO_PROJ_DIM = 32
PROTO_PROJ_ACT = "gelu"

PROTO_CORE_MODE = "despl_pred_agree_hard"
PROTO_FG_THRESH = 0.90
PROTO_BG_THRESH = 0.10
PROTO_PRED_FG_THRESH = 0.60
PROTO_PRED_BG_LOW = 0.20
PROTO_PRED_BG_HIGH = 0.60
PROTO_EASY_BG_THRESH = 0.20

PROTO_USE_HARD_BG_ONLY = True
PROTO_USE_BG_RING = True
PROTO_BG_RING_RADIUS = 3
PROTO_USE_DISAGREE_MAP = True
PROTO_DISAGREE_THRESH = 0.15
PROTO_USE_NDR_RESIDUAL_FOR_HARD = True
PROTO_NDR_RESIDUAL_Q = 0.80

PROTO_MIN_FG_PIXELS = 16
PROTO_MIN_BG_PIXELS = 32
PROTO_MAX_PIXELS_PER_CLASS = 256
PROTO_MAX_FG_PIXELS = 128
PROTO_MAX_BG_PIXELS = 256

PROTO_PIXEL_LOSS_MODE = "hard_margin"
PROTO_PIXEL_MARGIN = 0.20
PROTO_SEP_MARGIN = 0.20
PROTO_ALIGN_WEIGHT = 1.00
PROTO_SEP_WEIGHT = 0.25
PROTO_PIXEL_FG_WEIGHT = 0.30
PROTO_PIXEL_BG_WEIGHT = 1.00

PROTO_WARMUP_EPOCH = 6
PROTO_RAMP_START_EPOCH = 7
PROTO_RAMP_END_EPOCH = 15
PROTO_AFTER_RESET_SCALE = 0.0
PROTO_DETACH_MASK = True
PROTO_DETACH_PIXEL_PROTOTYPE = True
PROTO_SKIP_INVALID = True

MV_PROTO_DEBUG = True
