from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_long35_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_dagp_uncgate_csd_v1r_rast_v12_esa_asym_clean35_lrfloor_2e5"

# Replace only the old NDR residual branch. Keep old DAGP-Safe coarse anchor unchanged.
HEAD_TYPE = "dagp_safe_csd_v1r"
head_type = "dagp_safe_csd_v1r"
USE_DAGP_SAFE_HEAD = True
USE_DAGP_HEAD = False
USE_CSD_V1R = True
CSD_V1R_VERSION = "old_dagp_safe_coarse_anchor_residual_only"

USE_CSD_DECODER = False
USE_NDR_BRANCH = False
USE_NDR_COARSE_AUX = False
USE_NDR_V2 = False
NDR_VERSION = "off_for_csd_v1r"

# CSD-v1R residual-only branch.
CSD_V1R_SEM_DIM = 64
CSD_V1R_DETAIL_DIM = 32
CSD_V1R_FUSION_DIM = 64
CSD_V1R_WARMUP_EPOCH = 6
CSD_V1R_RAMP_START_EPOCH = 7
CSD_V1R_RAMP_END_EPOCH = 15
CSD_V1R_BETA_MAX = 0.05
CSD_V1R_RESIDUAL_CLIP = 2.0
CSD_V1R_ZERO_INIT_RESIDUAL = True
CSD_V1R_USE_GATE_BIAS_INIT = True
CSD_V1R_GATE_BIAS_INIT = -2.0
CSD_V1R_BG_SUPPRESS_STRENGTH = 0.70

# CSD-v1R training auxiliaries.
CSD_V1R_USE_COARSE_AUX = True
LAMBDA_CSD_V1R_COARSE_AUX = 0.50
CSD_V1R_USE_BG_DETAIL_LOCK = True
CSD_V1R_BG_DETAIL_LOCK_WEIGHT = 0.005
CSD_V1R_BG_CORE_THRESH = 0.50
CSD_V1R_BG_LOW_TARGET_THRESH = 0.15
CSD_V1R_BG_LOW_TARGET_WEIGHT_THRESH = 0.50
CSD_V1R_USE_BOUNDARY_AUX = False
CSD_V1R_BOUNDARY_AUX_WEIGHT_MAX = 0.0

# Keep the Long35 DABE-PU + RAST-v1.2 + ESA-Asym protocol explicitly locked.
MAX_EPOCH = 35
max_epoch = 35
SAVE_EVERY_EPOCH = True
SAVE_INTERVAL = 1

DINO = dict(DINO)
DINO["lr"] = 0.0006
LR = 0.0006
LR_POLICY = "step_floor"
USE_LR_FLOOR = True
LR_FLOOR = 2e-5
LR_LINEAR_STAGE1_EPOCHS = 19
LR_LINEAR_STAGE2_EPOCHS = 0
LR_FLOOR_MODE = "global"
LR_FLOOR_APPLY_AFTER_SCHEDULER_STEP = True
LR_FLOOR_APPLY_AFTER_FINETUNE_RESET = True

FINETUNE_RESET_EPOCH = 20
FINETUNE_RESET_TIMING = "after_epoch"
FINETUNE_RESET_REBUILD_OPTIMIZER = True
FINETUNE_RESET_REBUILD_SCHEDULER = True
FINETUNE_RESET_GLOBAL_STEP = True
FINETUNE_RESET_TEACHER = True
FINETUNE_RESET_FORCE_LR_FLOOR = True
FINETUNE_RESET_LR = 2e-5

USE_DABE_PU = True
DABE_PU_VERSION = "pu_v11"
DABE_PU_ROOT = "../datasets/cache/dabe_pu_v11_pseudo_cache/dinov1-s8"
P_INIT_MODE = "dabe_pu_v11_desplsched"
P_INIT_DABE_WEIGHT = 1.0
P_INIT_DESPL_WEIGHT = 0.0
P_INIT_FIXED_WEIGHT = 0.0

USE_DABE_PSEUDO = False
USE_DESPL_PSEUDO = False
use_despl_pseudo = False
USE_DESPL_LIGHT_CACHE = False
use_despl_light_cache = False
USE_DESPL_PAPER_CACHE = False
use_despl_paper_cache = False
USE_FIXED_IN_PSEUDO = False
use_fixed_in_pseudo = False
fixed_used_for_training = False

TEACHER_FUSION_MODE = "dabe_pu_despl_sched"
USE_DABE_PU_DESPL_SCHEDULE = True
USE_DABE_PU_STATIC_LOSS = True
USE_TEACHER_BINARY_FULL_LOSS = True
USE_TEACHER_SOFT_FULL_LOSS = False
TEACHER_TARGET_MODE = "binary"
USE_TEACHER_CONF_LOSS = False
USE_DABE_PU_GROUP_BALANCED_STATIC = False
USE_TEACHER_CONF_BALANCED = False
USE_DABE_OEM = False
USE_DABE_PU_SEED_STATIC_LOSS = False
USE_DABE_OEM_DYNAMIC_EXTENT = False
DABE_PU_STATIC_TARGET_MODE = "soft"
USE_DABE_PU_HARD_STATIC_TARGET = False

DABE_PU_DESPL_STAGE_START = 1
DABE_PU_DESPL_STAGE_END = 20
DABE_PU_DESPL_STATIC_START = 1.0
DABE_PU_DESPL_STATIC_END = 0.05
DABE_PU_DESPL_TEACHER_START = 0.0
DABE_PU_DESPL_TEACHER_END = 0.95
DABE_PU_DESPL_TEACHER_ONLY_START = 21

USE_RAST = True
RAST_VERSION = "v1.2_esa_asym_csd_v1r"
RAST_START_EPOCH = 7
RAST_RAMP_END_EPOCH = 15
RAST_STOP_EPOCH = 21
RAST_CONFLICT_TEACHER_MULT = 0.20
RAST_EXTENT_TEACHER_MULT = 1.00
RAST_UNKNOWN_TEACHER_MULT = 0.50
RAST_OTHER_TEACHER_MULT = 1.00
RAST_POST_RESET_ENABLE = False
RAST_POST_RESET_SCALE = 0.0
RAST_POST_RESET_CONFLICT_ONLY = False
RAST_POST_RESET_USE_STATIC_LOSS = False
RAST_APPLY_TO_FINAL = True
RAST_APPLY_TO_COARSE_AUX = True
RAST_APPLY_TO_BASE_AUX = True
RAST_WEIGHTED_LOSS_NORMALIZE = True

USE_ESA_ASYM = True
ESA_ASYM_VERSION = "extent_teacher_bg_routing_v1"
ESA_ASYM_START_EPOCH = 7
ESA_ASYM_RAMP_END_EPOCH = 15
ESA_ASYM_STOP_EPOCH = 21
ESA_EXTENT_TEACHER_FG_MULT = 1.00
ESA_EXTENT_TEACHER_BG_MULT = 0.50
ESA_USE_DINO_MARGIN = True
ESA_MARGIN_FG_LIKE = 0.05
ESA_MARGIN_BG_LIKE = -0.05
ESA_EXTENT_TEACHER_BG_FG_LIKE_MULT = 0.25
ESA_EXTENT_TEACHER_BG_AMBIG_MULT = 0.50
ESA_EXTENT_TEACHER_BG_BG_LIKE_MULT = 1.00
ESA_TOUCH_UNKNOWN = False
ESA_UNKNOWN_TEACHER_MULT = 0.50
ESA_FEATURE_SIZE = 37
ESA_DETACH_MASK = True
ESA_DETACH_PROTO = True
USE_ESA_DIAGNOSTIC = True
ESA_DIAG_LOG_INTERVAL_EPOCH = 1

# Explicitly keep unrelated experimental branches off.
USE_LCEG = False
USE_LCEG_DIAGNOSTIC = False
LCEG_LAMBDA_MAX = 0.0
USE_TCE = False
USE_TCE_DIAGNOSTIC = False
TCE_LAMBDA_MAX = 0.0
USE_HBNS_LITE = False
HBNS_LAMBDA_MAX = 0.0
USE_EPR_POS = False
EPR_LAMBDA_MAX = 0.0
USE_DARE = False
USE_DABE_AWARE_LOSS = False
USE_DABE_TVERSKY_LOSS = False
USE_DABE_AREA_GUARD = False
USE_PROTO_CONTRAST = False
LAMBDA_PROTO_MAX = 0.0
USE_MULTI_VIEW_FEATURE = False
use_multi_view_feature = False
MULTI_VIEW_TYPES = []
multi_view_types = []
USE_VIEW_CONSISTENCY = False
use_view_consistency = False
LAMBDA_VIEW_MAX = 0.0
lambda_view_max = 0.0
GKD_MODE = "off"
USE_GKD_LITE = False
USE_TADR_ROUTER = False
