from configs.dinov1_s8_dabepu_v11_egsa_r2_pure_dagp_uncgate_ndr_long45_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = (
    "dinov1_s8_dabepu_v11_egsa_r2b_signaware_dagp_uncgate_ndr_"
    "stage20_lrfloor_2e5"
)
MAX_EPOCH = 20
max_epoch = 20
SAVE_EVERY_EPOCH = True
SAVE_INTERVAL = 1

SOURCE_ARBITER_VERSION = "egsa_r2b_signaware_directional_v1"
SOURCE_ARBITER_MODE = "sign_aware_pure_loss_space"
SOURCE_ARBITER_STAGE = "stage20"
SOURCE_ARBITER_RESUME_ONLY = True
SOURCE_ARBITER_REQUIRED_RESUME_EPOCH = 6
SOURCE_ARBITER_SKIP_AFTER_EPOCH_RESET = True

SOURCE_ARBITER_USE_ECST_TEACHER_MAP = False
SOURCE_ARBITER_USE_STRUCTURED_EVIDENCE = True
SOURCE_ARBITER_ECST_AUDIT_ONLY = False
SOURCE_ARBITER_COMPUTE_R1_SHADOW_LOSS = False
SOURCE_ARBITER_LOG_PLAIN_VS_ECST_TEACHER = False

SOURCE_ARBITER_INPUT_CHANNELS = 18
SOURCE_ARBITER_OUTPUT_CHANNELS = 2
SOURCE_ARBITER_HIDDEN_1 = 32
SOURCE_ARBITER_HIDDEN_2 = 32
SOURCE_ARBITER_HIDDEN_3 = 16
SOURCE_ARBITER_DILATION = 2
SOURCE_ARBITER_ZERO_INIT_HEAD = True
SOURCE_ARBITER_POS_RESIDUAL_BOUND = 1.5
SOURCE_ARBITER_NEG_RESIDUAL_BOUND = 4.0

SOURCE_ARBITER_TRAIN_START_EPOCH = 7
SOURCE_ARBITER_TRAIN_RAMP_END_EPOCH = 15
SOURCE_ARBITER_TRAIN_STOP_EPOCH = 21
SOURCE_ARBITER_APPLY_START_EPOCH = 7
SOURCE_ARBITER_APPLY_RAMP_END_EPOCH = 15
SOURCE_ARBITER_APPLY_STOP_EPOCH = 46
SOURCE_ARBITER_FREEZE_AFTER_EPOCH = 20

SOURCE_ARBITER_UTILITY_MODE = "directional_gradient_alignment"
SOURCE_ARBITER_UTILITY_TAU = 0.05
SOURCE_ARBITER_UTILITY_MIN_FUTURE_MOVE = 0.03
SOURCE_ARBITER_UTILITY_MIN_SEMANTIC_MOVE = 0.05
SOURCE_ARBITER_UTILITY_REQUIRE_DIRECTION_AGREEMENT = True
SOURCE_ARBITER_UTILITY_FUTURE_WEIGHT_SCALE = 0.15
SOURCE_ARBITER_UTILITY_SEMANTIC_WEIGHT_SCALE = 0.25

SOURCE_ARBITER_UTILITY_DABE_FG_THRESH = 0.70
SOURCE_ARBITER_UTILITY_DABE_BG_THRESH = 0.30
SOURCE_ARBITER_UTILITY_DABE_WEIGHT_THRESH = 0.70
SOURCE_ARBITER_UTILITY_USE_FG_CORE = True
SOURCE_ARBITER_UTILITY_USE_BG_CORE = True

SOURCE_ARBITER_MIN_MEMORY_AGE_EPOCH = 1
SOURCE_ARBITER_MAX_MEMORY_AGE_EPOCH = 2
SOURCE_ARBITER_UTILITY_MIN_HISTORY = 3
SOURCE_ARBITER_UTILITY_MAX_VIEW_DIFF = 0.15
SOURCE_ARBITER_UTILITY_VIEW_TAU = 0.05

SOURCE_ARBITER_UTILITY_SEPARATE_SIGN_BRANCHES = True
SOURCE_ARBITER_UTILITY_CLASS_BALANCE = "audit_v2_fixed_sqrt_inverse"
SOURCE_ARBITER_UTILITY_CLASS_WEIGHT_MIN = 0.5
SOURCE_ARBITER_UTILITY_CLASS_WEIGHT_MAX = 4.0

SOURCE_ARBITER_AUDIT_POS_MIN_VALID_PIXELS = 10000
SOURCE_ARBITER_AUDIT_POS_MIN_HARD_MINORITY_PIXELS = 500
SOURCE_ARBITER_AUDIT_POS_MIN_HARD_MINORITY_RATIO = 0.01
SOURCE_ARBITER_AUDIT_POS_MIN_SOFT_MINORITY_MASS = 2000.0
SOURCE_ARBITER_AUDIT_POS_MIN_MINORITY_IMAGES = 128
SOURCE_ARBITER_AUDIT_POS_MIN_ACTIVE_BATCH_RATIO = 0.90

SOURCE_ARBITER_AUDIT_NEG_MIN_VALID_PIXELS = 50000
SOURCE_ARBITER_AUDIT_NEG_MIN_HARD_MINORITY_PIXELS = 1000
SOURCE_ARBITER_AUDIT_NEG_MIN_HARD_MINORITY_RATIO = 0.01
SOURCE_ARBITER_AUDIT_NEG_MIN_SOFT_MINORITY_MASS = 2000.0
SOURCE_ARBITER_AUDIT_NEG_MIN_MINORITY_IMAGES = 256
SOURCE_ARBITER_AUDIT_NEG_MIN_ACTIVE_BATCH_RATIO = 0.99

SOURCE_ARBITER_AUDIT_MAX_TOP1P_IMAGE_SHARE = 0.25
SOURCE_ARBITER_AUDIT_MAX_TOP10P_IMAGE_SHARE = 0.60

SOURCE_ARBITER_LAMBDA_UTILITY = 1.0
SOURCE_ARBITER_LAMBDA_PRIOR = 0.10
SOURCE_ARBITER_LAMBDA_MASS = 0.01
SOURCE_ARBITER_LAMBDA_SMOOTH = 0.005
SOURCE_ARBITER_MASS_TOLERANCE = 0.30

SOURCE_ARBITER_POST_RESET_STATIC_PRIOR = 0.05
SOURCE_ARBITER_POST_RESET_TEACHER_PRIOR = 0.95
SOURCE_ARBITER_KEEP_TEMPORAL_MEMORY_AFTER_RESET = True
SOURCE_ARBITER_RELEASE_ROUTE_MEMORY_AFTER_FREEZE = True
SOURCE_ARBITER_RELEASE_UTILITY_EVALUATOR_AFTER_FREEZE = True

SOURCE_ARBITER_REQUIRE_TARGET_AUDIT = True
SOURCE_ARBITER_TARGET_AUDIT_SCHEMA = "egsa_r2b_target_audit_v2"
SOURCE_ARBITER_TARGET_AUDIT_PATH = (
    "../workdir/"
    "dinov1_s8_dabepu_v11_egsa_r2b_signaware_dagp_uncgate_ndr_"
    "stage20_lrfloor_2e5/audit_r2b_v2/summary.json"
)
SOURCE_ARBITER_TARGET_AUDIT_SOURCE_CKPT = (
    "../workdir/13-egsa_r1-long45/train/ckpt/epoch_006.pth"
)
SOURCE_ARBITER_TARGET_AUDIT_SOURCE_SHA256 = (
    "ef8f445aa6f440d0540e8546785b01cd22018092b3557f4a3cb4dffe0065dca5"
)
SOURCE_ARBITER_TARGET_AUDIT_REQUIRE_PASS = True
SOURCE_ARBITER_TARGET_AUDIT_MINI_RUN_MAX_EPOCH = 8

SOURCE_ARBITER_AREA_MONITOR_ONLY = True
SOURCE_ARBITER_AREA_STOP_PATIENCE = 2
SOURCE_ARBITER_PAIRED_R1_LOG = (
    "../workdir/13-egsa_r1-long45/train/train.log"
)
SOURCE_ARBITER_MIN_PAIRED_R1_AREA_RATIO = 0.85
SOURCE_ARBITER_MIN_ABSOLUTE_AREA = 0.115
SOURCE_ARBITER_POST_RESET_MIN_EPOCH20_AREA_RATIO = 0.85
SOURCE_ARBITER_STOP_NEG_TEACHER_PREFERRED_MAX = 0.99
SOURCE_ARBITER_STOP_NEG_DABE_PREFERRED_MIN = 0.01
SOURCE_ARBITER_STOP_NEG_DABE_RECALL_MIN = 0.20
SOURCE_ARBITER_STOP_NO_NEG_CORRECTION_PATIENCE = 2
SOURCE_ARBITER_STOP_NEG_CORRECTION_MIN_RATIO = 0.01
SOURCE_ARBITER_STOP_CONFLICT_GATE_TOLERANCE = 1e-6
SOURCE_ARBITER_STOP_NEG_SATURATION_MAX = 0.60
SOURCE_ARBITER_STOP_APPLIED_GATE_NEAR_ONE = 0.99
SOURCE_ARBITER_STOP_PERFORMANCE_PATIENCE = 3
SOURCE_ARBITER_STOP_FM_MATERIAL_DROP = 0.01

# R2b keeps the source temporal evidence alive through the long-stage tail.
ECST_MEMORY_UPDATE_END_EPOCH = 45
ECST_STOP_EPOCH = 46
ECST_RESET_MEMORY_AT_FINETUNE_RESET = False

# Epoch21-45 remains a 5/95 source mixture instead of teacher-only.
DABE_PU_DESPL_TEACHER_ONLY_START = 46
DABE_PU_DESPL_STAGE_END = 20
DABE_PU_DESPL_STATIC_END = 0.05
DABE_PU_DESPL_TEACHER_END = 0.95

ECST_APPLY_TO_FINAL = False
ECST_APPLY_TO_COARSE_AUX = False
ECST_APPLY_TO_BASE_AUX = False
