from configs.dinov1_s8_despl_only_dagp_safe_uncgate_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_dagp_uncgate_30e_orig20_hold5_reset26"

MAX_EPOCH = 30
FINETUNE_RESET_EPOCH = 26

LR_POLICY = "step_floor"
USE_LR_FLOOR = True
LR_FLOOR = 2e-5

TEACHER_FUSION_MODE = "orig20_hold_until_reset"
FUSION_ORIG_DECAY_EPOCHS = 20
FUSION_HOLD_FIXED_WEIGHT = 0.05

HEAD_TYPE = "dagp_safe"
USE_DAGP_SAFE_HEAD = True

DAGP_SAFE_HIDDEN = 64
DAGP_SAFE_TOPK = 12
DAGP_SAFE_TAU = 0.07
DAGP_SAFE_ALPHA_MAX = 0.05
DAGP_SAFE_GAMMA_MAX = 0.03
DAGP_SAFE_WARMUP_EPOCH = 6
DAGP_SAFE_RAMP_START_EPOCH = 7
DAGP_SAFE_RAMP_END_EPOCH = 15

DAGP_SAFE_USE_PROB_GATE = True
DAGP_SAFE_PROB_GATE_SIGMA = 0.25

DAGP_SAFE_USE_UNCERTAINTY_OUTPUT_GATE = True
DAGP_SAFE_UNCERTAINTY_POWER = 1.0
DAGP_SAFE_UNCERTAINTY_MIN = 0.0
DAGP_SAFE_UNCERTAINTY_MAX = 1.0
DAGP_SAFE_UNCERTAINTY_DETACH = True

USE_BASE_AUX_LOSS = True
LAMBDA_BASE_AUX = 0.5
LAMBDA_BASE_AUX_AFTER_RESET = 0.3
BASE_AUX_NORMALIZE = True
