from configs.dinov1_s8_despl_only_teacher_cache import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_despl_only_gkd_lite"

GKD_MODE = "reweight"
USE_GKD_LITE = True

# Keep the current best DESPL-only route unchanged.
HEAD_TYPE = "simple"
USE_GATED_CONTEXT_HEAD = False

USE_DESPL_PSEUDO = True
USE_DESPL_LIGHT_CACHE = True
P_INIT_MODE = "despl_only"
P_INIT_DESPL_WEIGHT = 1.0
P_INIT_FIXED_WEIGHT = 0.0

USE_QRA = False
USE_CCR = False
USE_DREPP = False
USE_DRE_SAFE_PRIOR = False
USE_DESPL_PAPER_CACHE = False

PSEUDO_USE_GCM = False
USE_GCM = False
PSEUDO_USE_TEACHER = False
PSEUDO_USE_LOCAL_ATTN = False

USE_PSTA = False
USE_MNP = False
DINO_USE_LORA = False
USE_CNN_DETAIL_BRANCH = False
USE_AFF = False
USE_DUAL_FG_BG_HEAD = False
USE_BOUNDARY_HEAD = False

LAMBDA_MNP = 0.0
LAMBDA_LOCAL = 0.0
LAMBDA_PSTA = 0.0
LAMBDA_CONTRAST = 0.0
LAMBDA_BOUNDARY = 0.0
LAMBDA_ENTROPY = 0.0
LAMBDA_ANCHOR = 0.0

USE_DESPL_ANCHOR_PBCE = False
USE_LATE_DESPL_ANCHOR_LOSS = False
USE_PURE_DESPL_SUPERVISION = False
USE_FAST_TEACHER_FUSION = False
TEACHER_FUSION_MODE = "default"

# GKD-Lite parameters
GKD_Q_HIGH = 0.75
GKD_Q_NORMAL = 0.45

GKD_SAMPLE_W_HIGH = 1.15
GKD_SAMPLE_W_NORMAL = 1.00
GKD_SAMPLE_W_LOW = 0.60

GKD_PIXEL_W_MIN = 0.60
GKD_LATE_STRENGTH = 0.30
GKD_LOG_FIRST_BATCH = True
