from configs.dinov1_s8_dabepu_v11_dagp_uncgate_ndr_rast_v12_esa_asym_long35_lrfloor_2e5 import *  # noqa: F401,F403


EXP_NAME = "dinov1_s8_dabepu_v11_cacd_v1_base_rast_v12_esa_asym_long35_lrfloor_2e5"

HEAD_TYPE = "cacd_v1_base"
head_type = "cacd_v1_base"
USE_CACD = True
CACD_VERSION = "v1_base_last3_consensus_anchor_context_68"

# CACD feature contract: existing final attention key is F12; this cache stores F10/F11 only.
CACD_FEATURE_SIZE = 37
CACD_OUTPUT_SIZE = 68
CACD_DINO_CHANNELS = 384
CACD_IN_CHANNELS = 384
CACD_EXTRA_LAYER_INDICES = [9, 10]
CACD_FINAL_LAYER_INDEX = 11
CACD_EXTRA_FEATURE_CACHE_ROOT = (
    "../datasets/cache/features_cache_cacd/dinov1-s8/last3_input296"
)
CACD_EXTRA_FEATURE_DTYPE = "float32"
CACD_REUSE_EXISTING_FINAL_FEATURE = True

# Cross-layer consensus.
CACD_DIM = 96
CACD_GN_GROUPS = 8
CACD_ACT = "gelu"
CACD_ACTIVE_FROM_EPOCH1 = True
CACD_USE_HARD_WARMUP = False
CACD_USE_CROSS_LAYER_CONSENSUS = True
CACD_FUSION_ALPHA_MAX = 0.25
CACD_FUSION_ALPHA_INIT_LOGIT = -4.0
CACD_GATE_HIDDEN = 96
CACD_GATE_BIAS_INIT = 0.0
CACD_QC_DETACH = True
CACD_QC_EPS = 1e-6

# Reliable three-class anchor estimator.
CACD_USE_ANCHOR_HEAD = True
CACD_ANCHOR_CLASSES = 3
CACD_ANCHOR_FG_INDEX = 0
CACD_ANCHOR_BG_INDEX = 1
CACD_ANCHOR_AMBIG_INDEX = 2
CACD_ANCHOR_HIDDEN = 64
CACD_ANCHOR_LOSS_WEIGHT = 0.05
CACD_ANCHOR_MIN_PIXELS_PER_CLASS = 4
CACD_ANCHOR_LOSS_ALL_EPOCHS = True
CACD_ANCHOR_USE_EXTENT_LABEL = False
CACD_ANCHOR_USE_UNKNOWN_LABEL = False

# Multi-anchor context.
CACD_USE_MULTI_ANCHOR_CONTEXT = True
CACD_NUM_FG_SLOTS = 4
CACD_NUM_BG_SLOTS = 4
CACD_SLOT_DIM = 96
CACD_SLOT_INIT_SEED = 13579
CACD_SLOT_ATTN_DROPOUT = 0.0
CACD_ANCHOR_PRIOR_EPS = 1e-4
CACD_CONTEXT_HIDDEN = 192
CACD_CONTEXT_GATE_HIDDEN = 64
CACD_CONTEXT_FINAL_ZERO_INIT = True
CACD_CONTEXT_DROPOUT = 0.0

# 37x37 semantic path plus a single 68x68 RGB/Sobel decoder.
CACD_CONTEXT_BLOCKS = 2
CACD_DETAIL_DIM = 32
CACD_DECODER_DIM = 96
CACD_DECODER_OUT_DIM = 64
CACD_USE_RGB_DETAIL = True
CACD_USE_SOBEL_DETAIL = True
CACD_USE_136_DECODER = False
CACD_USE_BOUNDARY_POST_REFINE = False

# Original Long35 segmentation group is preserved; only partial anchor CE is added.
CACD_USE_COARSE_AUX = True
LAMBDA_CACD_COARSE_AUX = 0.50
CACD_USE_ANCHOR_LOSS = True
CACD_USE_SLOT_DIVERSITY_LOSS = False
CACD_USE_RELATION_LOSS = False
CACD_USE_LOCAL_STRUCTURE_LOSS = False
CACD_USE_VIEW_LOSS = False
CACD_USE_ADAPTIVE_TEACHER = False
CACD_KEEP_ORIGINAL_TEACHER_SCHEDULE = True
CACD_KEEP_ORIGINAL_RESET = True

USE_CACD_DIAGNOSTIC = True
CACD_DIAG_LOG_INTERVAL_EPOCH = 1
CACD_SLOT_COLLAPSE_COS_THRESH = 0.98
CACD_SLOT_OVERLAP_WARN_THRESH = 0.90
CACD_CONTEXT_NOOP_THRESH = 1e-4
CACD_CONTEXT_EXPLODE_RATIO = 1.0

# Preserve the actual Long35 RAST/ESA protocol exactly.
USE_RAST = True
RAST_VERSION = "v1.2_esa_asym"
USE_ESA_ASYM = True
ESA_ASYM_START_EPOCH = 7
ESA_ASYM_RAMP_END_EPOCH = 15
ESA_ASYM_STOP_EPOCH = 21
ESA_POST_RESET_ENABLE = False

USE_DABE_PU = True
DABE_PU_VERSION = "pu_v11"
DABE_PU_STATIC_TARGET_MODE = "soft"
USE_TEACHER_BINARY_FULL_LOSS = True
USE_TEACHER_SOFT_FULL_LOSS = False
TEACHER_TARGET_MODE = "binary"
USE_TEACHER_CONF_LOSS = False
USE_DABE_PU_GROUP_BALANCED_STATIC = False
USE_DABE_OEM = False
MAX_EPOCH = 35
max_epoch = 35
SAVE_EVERY_EPOCH = True
SAVE_INTERVAL = 1

# CACD replaces the complete old decoder path and must not instantiate competing branches.
USE_DAGP_SAFE_HEAD = False
use_dagp_safe_head = False
USE_NDR_BRANCH = False
USE_NDR_V2 = False
USE_CSD_DECODER = False
USE_CSD_V1R = False
USE_PA_DAGP = False
USE_ESA_BER = False
USE_HR_BFR = False
USE_CSSD = False
USE_LCEG = False
USE_TCE = False
USE_HBNS_LITE = False
HBNS_LAMBDA_MAX = 0.0
USE_EPR_POS = False
EPR_LAMBDA_MAX = 0.0
USE_DARE = False
USE_PROTO_CONTRAST = False
LAMBDA_PROTO_MAX = 0.0
USE_TADR_ROUTER = False
USE_DABE_AWARE_LOSS = False
USE_DABE_TVERSKY_LOSS = False
USE_DABE_AREA_GUARD = False
USE_MULTI_LEVEL_FEATURE = False
USE_MULTI_VIEW_FEATURE = False
use_multi_view_feature = False
MULTI_VIEW_TYPES = []
multi_view_types = []
USE_VIEW_CONSISTENCY = False
use_view_consistency = False
GKD_MODE = "off"
USE_GKD_LITE = False
