from configs.dinov1_s8 import *  # noqa: F401,F403


EXP_NAME = "drepp_v1"

USE_DREPP = True
DREPP_CACHE_ROOT = "../datasets/cache/drepp_v1_pseudo_cache"
NPER_PSEUDO_BANK_ROOT = "../datasets/cache/nper_pseudo_bank"

DESPL_CORE_ONLY = True
FIXED_LOCAL_ONLY = True
USE_MEMORY = True
USE_TEACHER = True
USE_LOCAL_REFINE = True
USE_GLOBAL_BLEND = False

DREPP_CORE_FG_TH = 0.75
DREPP_CORE_BG_TH = 0.10
DREPP_FIXED_DILATION_RADIUS = 2
DREPP_FIXED_SIM_TH = 0.35
DREPP_FIXED_MAX_EXPAND_RATIO = 1.2
DREPP_FIXED_MAX_CC = 4
DREPP_FIXED_MIN_CC_AREA = 2
DREPP_FIXED_RECALL_VALUE = 0.65
DREPP_BOUNDARY_RADIUS = 2

DREPP_MEMORY_MARGIN = 0.03
DREPP_MEMORY_IOU_TH = 0.30
DREPP_MEMORY_CONF_TH = 0.45
DREPP_MEMORY_ALPHA = 0.20
DREPP_MEMORY_ALPHA_LATE = 0.35
DREPP_TEACHER_BETA_MAX = 0.35
DREPP_TEACHER_BETA_LATE = 0.65

DREPP_LOCAL_START_EPOCH = 6
DREPP_LOCAL_FG_TH = 0.70
DREPP_LOCAL_BG_TH = 0.30
DREPP_LOCAL_SIM_TH = 0.35
DREPP_LOCAL_BG_SIM_TH = 0.25
DREPP_LAMBDA_LOCAL = 0.05
DREPP_LAMBDA_ANCHOR = 0.0

USE_QRA = False
USE_CCR = False
USE_DESPL_PSEUDO = False
USE_DESPL_LIGHT_CACHE = False
FIXED_GLOBAL_BLEND = False

USE_GCM = False
PSEUDO_USE_GCM = False
PSEUDO_USE_TEACHER = False
PSEUDO_USE_LOCAL_ATTN = False

USE_PSTA = False
USE_MNP = False
DINO_USE_LORA = False
USE_CNN_DETAIL_BRANCH = False
USE_AFF = False
USE_DUAL_FG_BG_HEAD = False
USE_BOUNDARY_HEAD = False

LAMBDA_MNP = 0.0
LAMBDA_LOCAL = 0.0
LAMBDA_PSTA = 0.0
LAMBDA_CONTRAST = 0.0
LAMBDA_BOUNDARY = 0.0
LAMBDA_ENTROPY = 0.0
LAMBDA_ANCHOR = 0.0

HEAD_TYPE = "simple"
