EXP_NAME = "nper_ucod_v1"

DATA_ROOT = "../datasets/COD"
CACHE_ROOT = "../datasets/cache"
WORK_ROOT = "../workdir"

TRAIN_DATASETS = ["TR-CAMO", "TR-COD10K"]
VAL_DATASETS = ["TE-CAMO"]
TEST_DATASETS = ["CHAMELEON", "TE-CAMO", "TE-COD10K", "NC4K"]

SEED = 42
NUM_WORKERS = 4

INPUT_SIZE = 352
LOSS_SIZE = 352
EVAL_ORIGINAL_SIZE = True
THRESHOLD = 0.5

MAX_EPOCH = 40
BATCH_SIZE = 8
VAL_BATCH_SIZE = 1
ACCUM_STEPS = 1
USE_AMP = True

OPTIMIZER = "AdamW"
LR = 1e-4
LR_LORA = 2e-4
LR_DECODER = 1e-4
WEIGHT_DECAY = 1e-4
SCHEDULER = "cosine"
WARMUP_EPOCHS = 2

USE_EMA_TEACHER = True
EMA_MOMENTUM = 0.99

BACKBONE_KEY = "dinov1-s8"
DINO_MODEL_PATH = "../../workspace/weights/huggingface/facebook-dino-vits8"
DINO_PATCH_SIZE = 8
DINO_FREEZE_BASE = True
DINO_USE_LORA = True
DINO_LORA_RANK = 8
DINO_LORA_ALPHA = 16
DINO_LORA_DROPOUT = 0.0
DINO_LORA_TARGETS = ["q", "k", "v"]
DINO_LORA_TYPE = "msmr"
DINO_OUT_LAYERS = [3, 6, 9, 12]
DINO_ATTN_LAYERS = [6, 9, 12]

DINO = {
    "model_name": "facebook/dino-vits8",
    "model_path": DINO_MODEL_PATH,
    "patch_size": DINO_PATCH_SIZE,
    "pseudo_input_size": 224,
    "feature_input_size": 296,
    "bkg_th": 0.3,
    "lr": LR_DECODER,
}

USE_CNN_DETAIL_BRANCH = True
DETAIL_BRANCH = "resnet18_shallow"
DETAIL_PRETRAINED = True
DETAIL_ALLOW_RANDOM_INIT = False
DETAIL_FREEZE = False
DETAIL_OUT_CHANNELS = 128
RESNET18_AUTO_DOWNLOAD = True
RESNET18_WEIGHT_PATH = "../../workspace/weights/torchvision/resnet18-f37072fd.pth"
TORCHVISION_CACHE_DIR = "../../workspace/weights/torchvision"

DECODER = "aff_dual"
DECODER_CHANNELS = 256
USE_AFF = True
USE_DUAL_FG_BG_HEAD = True
USE_BOUNDARY_HEAD = True

USE_PSEUDO_BANK = True
PSEUDO_BANK_ROOT = "../datasets/cache/nper_pseudo_bank"
PSEUDO_USE_FIXED = True
PSEUDO_USE_DESPL = True
PSEUDO_USE_GCM = True
PSEUDO_USE_TEACHER = True
PSEUDO_USE_LOCAL_ATTN = True
FIXED_PSEUDO_ROOT = "../datasets/cache/pseudo_label_cache"

DESPL_GRID = 28
DESPL_LAMBDA_COLOR = 0.1
DESPL_COLOR_SIGMA = 0.1
DESPL_EIG_BINS = 50
DESPL_LOWCONF_ALPHA = 0.1
DESPL_AUGS = ["identity", "hflip", "vflip", "rot180"]

GCM_INPUT_SIZE = 224
GCM_GRID = 28
GCM_ATTN_LAYER = 12
GCM_SAR_KERNEL = 5
GCM_MCF_AUGS = ["identity", "hflip", "scale_0.75", "scale_1.25"]
GCM_STABILITY_TH = 0.45

USE_MNP = True
MNP_USE_LBP = True
MNP_USE_DOG = True
MNP_USE_SOBEL = True
MNP_USE_RESNET18 = True
MNP_RESNET18_FREEZE = True
MNP_ALLOW_RANDOM_RESNET = False
MNP_REGION_TH = 0.5
MNP_DILATE_KERNEL = 5
MNP_RANDOM_PATCH_K = 5
MNP_RANDOM_SAMPLE_N = 32

QUALITY_HIGH_TH = 0.70
QUALITY_MID_TH = 0.45
QUALITY_LOW_FILTER_TH = 0.25
HARD_SAMPLE_DOWN_WEIGHT = 0.3

ANCHOR_FG_TH = 0.70
ANCHOR_BG_TH = 0.20
ANCHOR_MIN_RATIO = 0.03

EVOLUTION_START_EPOCH = 12
TEACHER_MAX_WEIGHT = 0.30
INIT_MIN_WEIGHT = 0.20
ANCHOR_WEIGHT = 0.10
LOCAL_ATTN_WEIGHT = 0.15
QUALITY_TEMPERATURE = 0.5

USE_PSTA = False
PSTA_START_EPOCH = 6
PSTA_SCALES = [1.25, 1.0, 0.75]
PSTA_USE_COLOR_JITTER = True
PSTA_USE_GAUSSIAN_BLUR = True
PSTA_USE_LOCAL_CROP = True
PSTA_ALPHA = 0.5

LAMBDA_PSEUDO = 1.0
LAMBDA_ANCHOR = 0.5
LAMBDA_MNP = 0.05
LAMBDA_LOCAL = 0.2
LAMBDA_PSTA = 0.0
LAMBDA_CONTRAST = 0.05
LAMBDA_BOUNDARY = 0.2
LAMBDA_ENTROPY = 0.01

BEST_DATASET = "TE-CAMO"
BEST_METRIC = "M"
BEST_MODE = "min"
SAVE_INTERVAL = 5
